"""Trade engine - orchestrates signal processing, Claude decision, and execution."""

import asyncio
import hashlib
import logging
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml

from app.config import get
from app.database import insert_trade, get_stats, log_signal, insert_position, get_position_count, get_open_position_for_signal, get_open_positions, TradeReason
from app.models import WebhookSignal, ClaudeDecision
from app.services.claude_decision import get_claude_decision
from app.services.jupiter_client import JupiterClient
from app.services.news_service import NewsService
from app.services.kamino_client import KaminoClient
from app.services.confluence_filter import get_confluence_filter
from app.services.dry_run_manager import get_dry_run_manager
from app.services.sol_risk_manager import get_sol_risk_manager
from app.services.paper_trading import get_paper_trader
from app.services.telegram_service import TelegramService
from app.services.wallet_service import WalletService

logger = logging.getLogger("bot.engine")

# Duplicate signal detection
_recent_signals: dict[str, float] = {}

# CLOSE-signal filter counters — most CLOSEs (~92%) have no matching position
# (Pine indicators emit CLOSE on every bar where exit-condition is true). The
# bot already drops them correctly; this counter lets us track filter volume
# without spamming logs/Telegram on each one.
_close_filter_stats = {
    "ignored": 0,           # CLOSE arrived but no open position matches
    "blocked_too_new": 0,   # matched but position younger than min_hold_seconds
    "blocked_low_move": 0,  # matched but price hasn't moved enough to clear fees
    "last_summary_total": 0,
}
_CLOSE_FILTER_SUMMARY_EVERY = 25  # emit summary INFO line every N filtered signals


def _bump_close_filter(reason: str) -> None:
    """Increment a CLOSE-filter counter and emit a summary line every N events."""
    if reason in _close_filter_stats:
        _close_filter_stats[reason] += 1
    total = (
        _close_filter_stats["ignored"]
        + _close_filter_stats["blocked_too_new"]
        + _close_filter_stats["blocked_low_move"]
    )
    if total - _close_filter_stats["last_summary_total"] >= _CLOSE_FILTER_SUMMARY_EVERY:
        logger.info(
            f"CLOSE filter summary (since startup): "
            f"{_close_filter_stats['ignored']} ignored (no position), "
            f"{_close_filter_stats['blocked_too_new']} blocked (too new), "
            f"{_close_filter_stats['blocked_low_move']} blocked (low move)"
        )
        _close_filter_stats["last_summary_total"] = total


# ── TP/SL sweep overrides (config_tpsl_overrides.yaml) ───────────────────────
_TPSL_OVERRIDES_PATH = Path(__file__).resolve().parents[2] / "config_tpsl_overrides.yaml"
_tpsl_overrides_cache: dict = {}
_tpsl_overrides_mtime: float = 0.0


def _load_tpsl_overrides() -> dict:
    """Load strategy_token_tf_overrides from config_tpsl_overrides.yaml with mtime caching.

    Returns shape: {strategy: {token: {tf: {atr_sl_mult, atr_tp_mult}}}}
    Returns {} if the file doesn't exist or fails to parse.
    """
    global _tpsl_overrides_cache, _tpsl_overrides_mtime
    try:
        mtime = os.path.getmtime(_TPSL_OVERRIDES_PATH)
    except OSError:
        if _tpsl_overrides_cache:
            _tpsl_overrides_cache = {}
            _tpsl_overrides_mtime = 0.0
        return {}

    if mtime == _tpsl_overrides_mtime:
        return _tpsl_overrides_cache

    try:
        with open(_TPSL_OVERRIDES_PATH) as f:
            data = yaml.safe_load(f) or {}
        _tpsl_overrides_cache = data.get("strategy_token_tf_overrides", {}) or {}
        _tpsl_overrides_mtime = mtime
        logger.info(f"Loaded TP/SL sweep overrides: {sum(len(t) for t in _tpsl_overrides_cache.values())} token slots")
    except Exception as e:
        logger.warning(f"Failed to load {_TPSL_OVERRIDES_PATH}: {e}")
        _tpsl_overrides_cache = {}
        _tpsl_overrides_mtime = mtime  # don't retry until file changes
    return _tpsl_overrides_cache


# ── Tiered position sizing overrides (config_sizing_overrides.yaml) ──────────
# Seeded & regenerated by backtesting/nightly.py write_sizing_overrides().
_SIZING_OVERRIDES_PATH = Path(__file__).resolve().parents[2] / "config_sizing_overrides.yaml"
_sizing_overrides_cache: dict = {}
_sizing_overrides_mtime: float = 0.0


def _load_sizing_overrides() -> dict:
    """Load strategy_token_tf_sizes from config_sizing_overrides.yaml with mtime caching.

    Returns shape: {strategy: {token: {tf: {tier, size_pct, pf, source}}}}
    """
    global _sizing_overrides_cache, _sizing_overrides_mtime
    try:
        mtime = os.path.getmtime(_SIZING_OVERRIDES_PATH)
    except OSError:
        if _sizing_overrides_cache:
            _sizing_overrides_cache = {}
            _sizing_overrides_mtime = 0.0
        return {}

    if mtime == _sizing_overrides_mtime:
        return _sizing_overrides_cache

    try:
        with open(_SIZING_OVERRIDES_PATH) as f:
            data = yaml.safe_load(f) or {}
        _sizing_overrides_cache = data.get("strategy_token_tf_sizes", {}) or {}
        _sizing_overrides_mtime = mtime
        slots = sum(len(tfs) for toks in _sizing_overrides_cache.values() for tfs in toks.values())
        logger.info(f"Loaded sizing tier overrides: {slots} strategy/token/tf slots")
    except Exception as e:
        logger.warning(f"Failed to load {_SIZING_OVERRIDES_PATH}: {e}")
        _sizing_overrides_cache = {}
        _sizing_overrides_mtime = mtime
    return _sizing_overrides_cache


# Map Pine `_strat` string (e.g. "EMA Ribbon v1.0") → backtest canonical name.
# Backtest uses short names; Pine sends full "<Name> v<ver>". Keep explicit — easier to debug than regex.
_STRATEGY_NAME_ALIASES = {
    "ema ribbon": "EMA Ribbon",
    "stoch rsi": "Stoch RSI",
    "fvg": "FVG",
    "vwap dev": "VWAP Dev",
    "vwap deviation": "VWAP Dev",
    "liq sweep": "Liq Sweep",
    "liquidity sweep": "Liq Sweep",
    "donchian": "Donchian",
    "donchian breakout": "Donchian",
}


def _normalize_strategy_name(raw: Optional[str]) -> Optional[str]:
    """'EMA Ribbon v1.0' → 'EMA Ribbon'. Returns None if no match."""
    if not raw:
        return None
    # Strip trailing " v<digits>..." version tag
    base = raw.strip()
    for tag_sep in (" v", " V"):
        idx = base.rfind(tag_sep)
        if idx > 0 and idx < len(base) - 1 and base[idx + 2].isdigit():
            base = base[:idx]
            break
    return _STRATEGY_NAME_ALIASES.get(base.lower(), base)


# Pine `timeframe.period` emits raw resolution codes. Backtest uses human labels.
_TIMEFRAME_ALIASES = {
    "15": "15m", "15m": "15m",
    "60": "1H",  "1h": "1H", "1H": "1H",
    "240": "4H", "4h": "4H", "4H": "4H",
    "D": "1D",   "1D": "1D", "1d": "1D",
}


def _normalize_timeframe(raw: Optional[str]) -> Optional[str]:
    """'240' → '4H', '60' → '1H'. Returns input unchanged if not mapped."""
    if not raw:
        return None
    return _TIMEFRAME_ALIASES.get(raw.strip(), raw)


def get_sizing_override(strategy: Optional[str], symbol: Optional[str],
                        timeframe: Optional[str]) -> Optional[dict]:
    """Look up tier sizing for this (strategy, token, tf). Returns {tier, size_pct, pf} or None."""
    strat = _normalize_strategy_name(strategy)
    tf = _normalize_timeframe(timeframe)
    if not (strat and symbol and tf):
        return None
    token = symbol.upper().replace("USDT", "").replace("USD", "")
    slot = _load_sizing_overrides().get(strat, {}).get(token, {}).get(tf)
    if not slot:
        return None
    return slot


def _strip_pair(symbol: str) -> str:
    """Normalise 'BONKUSDT' → 'BONK' for correlation lookups."""
    return symbol.upper().replace("USDT", "").replace("USD", "")


def correlation_check(symbol: str) -> Optional[dict]:
    """Check if opening a new long in `symbol` would exceed its correlation group cap.

    Returns None if allowed, or a dict {group, limit, held: [tokens]} if blocked.
    """
    cfg = get("correlation") or {}
    if not cfg.get("enabled"):
        return None
    groups = cfg.get("groups") or {}

    tok = _strip_pair(symbol)
    # Find which group this token belongs to (first match wins)
    group_name = None
    group_cfg = None
    for gname, gcfg in groups.items():
        if tok in {t.upper() for t in (gcfg.get("tokens") or [])}:
            group_name = gname
            group_cfg = gcfg
            break
    if group_name is None:
        return None  # untracked token, no cap

    limit = int(group_cfg.get("max_concurrent", 99))
    members = {t.upper() for t in (group_cfg.get("tokens") or [])}
    held = [
        _strip_pair(p.get("symbol", ""))
        for p in get_open_positions()
        if _strip_pair(p.get("symbol", "")) in members
    ]
    # Don't double-count: if an open position already exists on the same symbol,
    # this BUY is likely a pyramid/add — let Claude + risk manager handle that,
    # correlation cap only applies to *new* distinct symbols.
    distinct_held = set(held) - {tok}
    if len(distinct_held) >= limit:
        return {
            "group": group_name,
            "limit": limit,
            "held": sorted(distinct_held),
            "token": tok,
        }
    return None


# =============================================================================
# SIGNAL PRIORITY QUEUE
# =============================================================================

class SignalQueue:
    """Batches simultaneous signals and processes highest confidence first.

    When multiple alerts fire on the same candle close (e.g., 3 tokens on 4H),
    they arrive within seconds. This queue collects them in a short window,
    then processes in confidence-descending order, checking budget before each.

    The webhook returns immediately (fire-and-forget) so TradingView doesn't
    timeout. Processing results are sent via Telegram notifications.
    """

    def __init__(self):
        self._queue: list[tuple[WebhookSignal, str]] = []  # (signal, source_ip)
        self._lock = asyncio.Lock()
        self._drain_task: Optional[asyncio.Task] = None

    async def enqueue(self, signal: WebhookSignal, source_ip: str):
        """Add signal to queue. Processing happens after batch window expires."""
        queue_cfg = get("signal_queue") or {}
        enabled = queue_cfg.get("enabled", True)
        batch_window = queue_cfg.get("batch_window_seconds", 5)

        if not enabled:
            # Queue disabled — process immediately (legacy behavior)
            engine = TradeEngine()
            try:
                await engine.process_signal(signal, source_ip)
            finally:
                await engine.shutdown()
            return

        async with self._lock:
            self._queue.append((signal, source_ip))

            # Start drain timer if not already running
            if self._drain_task is None or self._drain_task.done():
                self._drain_task = asyncio.create_task(self._drain_after(batch_window))

    async def _drain_after(self, delay: float):
        """Wait for batch window then process all queued signals."""
        await asyncio.sleep(delay)

        async with self._lock:
            batch = list(self._queue)
            self._queue.clear()

        if not batch:
            return

        # Sort by confidence (highest first)
        batch.sort(key=lambda x: x[0].confidence_score, reverse=True)

        logger.info(
            f"Signal queue draining {len(batch)} signals: "
            + ", ".join(f"{s.symbol}({s.confidence_score})" for s, _ in batch)
        )

        # Notify if multiple signals batched
        if len(batch) > 1:
            engine = TradeEngine()
            order_str = " > ".join(
                f"{s.symbol} {s.timeframe or '?'} (conf:{s.confidence_score})"
                for s, _ in batch
            )
            await engine.telegram.send_message(
                f"Signal Queue: {len(batch)} simultaneous signals\n"
                f"Priority order: {order_str}"
            )
            await engine.shutdown()

        # Process in priority order
        for signal, source_ip in batch:
            engine = TradeEngine()
            try:
                # Check position limit before processing
                risk_cfg = get("risk")
                max_positions = risk_cfg.get("max_open_positions", 3)
                open_count = get_position_count("open")
                if open_count >= max_positions and signal.signal_type.value == "BUY":
                    logger.warning(
                        f"Skipping {signal.symbol} (conf:{signal.confidence_score}) — "
                        f"max positions reached after higher-priority trades"
                    )
                    await engine.telegram.send_message(
                        f"Signal Queue: SKIPPED {signal.symbol} {signal.timeframe or ''} "
                        f"(conf:{signal.confidence_score}) — max positions reached"
                    )
                elif signal.signal_type.value == "BUY" and (corr := correlation_check(signal.symbol)):
                    logger.warning(
                        f"Skipping {signal.symbol} — correlation cap ({corr['group']} "
                        f"{len(corr['held'])}/{corr['limit']})"
                    )
                    await engine.telegram.send_message(
                        f"Signal Queue: SKIPPED {signal.symbol} — correlation cap "
                        f"({corr['group']} {len(corr['held'])}/{corr['limit']})"
                    )
                else:
                    await engine.process_signal(signal, source_ip)
            except Exception as e:
                logger.error(f"Signal queue processing error for {signal.symbol}: {e}")
            finally:
                await engine.shutdown()


# Singleton queue
_signal_queue: Optional[SignalQueue] = None


async def _confluence_timeout_handler(signal: WebhookSignal, source_ip: str):
    """Called when confluence timeout fires with on_timeout='execute'."""
    engine = TradeEngine()
    try:
        await engine.process_signal(signal, source_ip)
    finally:
        await engine.shutdown()


def get_signal_queue() -> SignalQueue:
    global _signal_queue
    if _signal_queue is None:
        _signal_queue = SignalQueue()
        # Wire confluence timeout callback
        from app.services.confluence_filter import get_confluence_filter
        cf = get_confluence_filter()
        cf.set_confirmed_callback(_confluence_timeout_handler)
    return _signal_queue


class TradeEngine:
    """Main trade orchestration engine."""

    def __init__(self):
        self.jupiter = JupiterClient()
        self.wallet = WalletService()
        self.telegram = TelegramService()
        self.news = NewsService()
        self.kamino = KaminoClient()
        self._running = True

    def is_duplicate(self, signal: WebhookSignal) -> bool:
        """Check if this signal is a duplicate within the configured window."""
        window = get("webhook", "duplicate_window_seconds", 30)
        sig_hash = hashlib.sha256(
            f"{signal.signal_type}:{signal.symbol}:{signal.entry_price_estimate}".encode()
        ).hexdigest()[:16]

        now = time.time()
        # Clean old entries
        expired = [k for k, v in _recent_signals.items() if now - v > window]
        for k in expired:
            del _recent_signals[k]

        if sig_hash in _recent_signals:
            logger.warning(f"Duplicate signal detected: {sig_hash}")
            return True

        _recent_signals[sig_hash] = now
        return False

    async def process_signal(self, signal: WebhookSignal, source_ip: str = "") -> dict:
        """Full signal processing pipeline."""
        result = {
            "status": "pending",
            "signal_type": signal.signal_type.value,
            "decision": None,
            "tx_signature": None,
            "error": None,
        }

        try:
            # Strategy name from indicator webhook (e.g. "FVG v1.0")
            strategy_label = signal.strategy or ""

            # 1. Log raw signal
            log_signal(signal.model_dump_json(), source_ip)

            # 2. Check duplicate
            if self.is_duplicate(signal):
                result["status"] = "duplicate"
                result["error"] = "Duplicate signal ignored"
                return result

            # 2.5. Correlation cap — block BUYs that would stack same-group exposure
            if signal.signal_type.value == "BUY":
                corr_block = correlation_check(signal.symbol)
                if corr_block:
                    msg = (
                        f"Correlation cap hit ({corr_block['group']}): "
                        f"holding {len(corr_block['held'])}/{corr_block['limit']} "
                        f"[{', '.join(corr_block['held'])}] — rejecting {corr_block['token']}"
                    )
                    logger.warning(msg)
                    await self.telegram.send_message(f"[CORR] {msg}")
                    insert_trade({
                        "signal_type": signal.signal_type.value,
                        "symbol": signal.symbol,
                        "action": "REJECT",
                        "amount_sol": 0,
                        "price_usd": signal.entry_price_estimate or 0,
                        "confidence_score": signal.confidence_score,
                        "claude_reasoning": "Correlation cap — not queried",
                        "wallet_address": self.wallet.public_key,
                        "notes": f"Correlation: {corr_block['group']} {len(corr_block['held'])}/{corr_block['limit']} held [{', '.join(corr_block['held'])}]",
                        "strategy": strategy_label,
                        "reason": TradeReason.CORRELATION_REJECT,
                    })
                    result["status"] = "correlation_blocked"
                    result["error"] = msg
                    return result

            # 3. Notify Telegram
            await self.telegram.notify_webhook_received(signal.model_dump())

            # 3.5. Confluence filter — hold signal until a second strategy confirms
            cf = get_confluence_filter()
            if cf.enabled:
                confirmed_signal = await cf.check(signal, source_ip)
                if confirmed_signal is None:
                    # Signal is being held — will be processed via timeout callback
                    result["status"] = "confluence_pending"
                    return result
                # Use the confirmed signal (may differ if higher-conf was picked)
                signal = confirmed_signal

            # 4. Gather context for Claude
            sol_price = await self.jupiter.get_sol_price()
            balance_sol = await self.wallet.get_balance_sol()
            usdc_balance = await self.wallet.get_usdc_balance()
            market_data = await self.jupiter.get_market_data()
            headlines = await self.news.get_headlines()

            # Check Kamino deposits (available purchasing power)
            kamino_usdc = 0.0
            if self.kamino.enabled:
                try:
                    kamino_pos = await self.kamino.get_user_position(self.wallet.public_key)
                    if kamino_pos.get("has_position"):
                        kamino_usdc = kamino_pos.get("deposited_usdc", 0.0)
                except Exception as e:
                    logger.warning(f"Could not check Kamino balance: {e}")

            # Total purchasing power = USDC in wallet + Kamino deposits + SOL value
            sol_usd_value = balance_sol * sol_price
            total_usd = usdc_balance + kamino_usdc + sol_usd_value
            # Tradeable USDC = wallet USDC + Kamino, minus reserve for future trades
            kamino_cfg = get("kamino") or {}
            usdc_reserve = kamino_cfg.get("reserve_usdc", 0.0)
            tradeable_usd = max(0, usdc_balance + kamino_usdc - usdc_reserve)

            # Get actual token price (use Jupiter price lookup, fall back to signal estimate)
            token_symbol = signal.symbol.replace("USDT", "").replace("USD", "")
            if token_symbol == "SOL":
                token_price = sol_price
            else:
                try:
                    token_price = await self.jupiter.get_token_price(token_symbol)
                except Exception:
                    token_price = signal.entry_price_estimate

            # 5. Check low balance shutdown (based on total USD, not just SOL)
            risk_cfg = get("risk")
            low_bal_usd = risk_cfg.get("low_balance_shutdown_usd", 50.0)
            if total_usd < low_bal_usd:
                result["status"] = "shutdown"
                result["error"] = (
                    f"Total balance too low: ${total_usd:.2f} "
                    f"(SOL: ${sol_usd_value:.2f}, USDC: ${usdc_balance:.2f}, Kamino: ${kamino_usdc:.2f})"
                )
                await self.telegram.notify_error(result["error"], "Low balance shutdown triggered")
                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "REJECT",
                    "amount_sol": 0,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": "Low balance shutdown",
                    "wallet_address": self.wallet.public_key,
                    "notes": f"Automatic shutdown - total ${total_usd:.2f} below ${low_bal_usd:.2f} threshold",
                    "strategy": strategy_label,
                    "reason": TradeReason.LOW_BALANCE,
                })
                return result

            # 6. Build risk params
            db_stats = get_stats()
            risk_params = {
                "max_purchase_sol": risk_cfg.get("max_purchase_sol", 5.0),
                "max_purchase_usd": risk_cfg.get("max_purchase_usd", 500.0),
                "max_leverage": risk_cfg.get("max_leverage", 5),
                "daily_loss_limit_percent": risk_cfg.get("daily_loss_limit_percent", 10.0),
                "low_balance_shutdown_usd": low_bal_usd,
                "today_pnl_usd": db_stats.get("today_pnl_usd", 0),
                "geo_risk_weight": get("geo_risk", "weight", 0.7),
                # Full balance breakdown for Claude
                "usdc_wallet": usdc_balance,
                "usdc_kamino": kamino_usdc,
                "tradeable_usd": tradeable_usd,
                "total_usd": total_usd,
            }

            # 7. Get Claude decision
            logger.info(
                f"Requesting Claude decision for {signal.signal_type.value} {signal.symbol} "
                f"(tradeable: ${tradeable_usd:.2f}, total: ${total_usd:.2f})"
            )
            claude_resp = await get_claude_decision(
                signal=signal,
                wallet_balance_sol=balance_sol,
                wallet_balance_usd=total_usd,
                sol_price=sol_price,
                market_data=market_data,
                news_headlines=headlines,
                risk_params=risk_params,
            )

            result["decision"] = claude_resp.model_dump()
            await self.telegram.notify_claude_decision(result["decision"], signal.signal_type.value)

            # 8. Execute based on decision
            if claude_resp.decision == ClaudeDecision.REJECT:
                result["status"] = "rejected"
                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "REJECT",
                    "amount_sol": 0,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": self.wallet.public_key,
                    "notes": f"Risk score: {claude_resp.risk_score}",
                    "strategy": strategy_label,
                    "reason": TradeReason.CLAUDE_REJECT,
                })
                return result

            # Determine trade parameters.
            # Precedence: Claude MODIFY > tiered sizing override > signal default.
            if claude_resp.decision == ClaudeDecision.MODIFY and claude_resp.modified_size_percent:
                size_pct = claude_resp.modified_size_percent
            else:
                tier_slot = get_sizing_override(signal.strategy, signal.symbol, signal.timeframe)
                if tier_slot:
                    size_pct = tier_slot["size_pct"]
                    logger.info(
                        f"Sizing tier {tier_slot['tier']} applied: {signal.strategy}/{signal.symbol}/"
                        f"{signal.timeframe} → {size_pct}% (PF={tier_slot.get('pf', '?')})"
                    )
                else:
                    size_pct = signal.suggested_position_size_percent
            leverage = (
                claude_resp.modified_leverage
                if claude_resp.decision == ClaudeDecision.MODIFY and claude_resp.modified_leverage
                else signal.suggested_leverage
            )

            # Apply risk caps
            leverage = min(leverage, risk_cfg.get("max_leverage", 5))
            size_pct = min(size_pct, risk_cfg.get("max_position_size_percent", 15))

            # Calculate trade amount in USD (base currency is USDC, not SOL)
            trade_usd = tradeable_usd * (size_pct / 100)
            max_purchase_usd = risk_cfg.get("max_purchase_usd", 500.0)
            trade_usd = min(trade_usd, max_purchase_usd)
            # ── SOL RISK MANAGER PRE-TRADE CHECK ──
            sol_rm = get_sol_risk_manager()
            risk_check = sol_rm.check_order(token_symbol, trade_usd, signal.signal_type.value)
            if not risk_check["allowed"]:
                result["status"] = "risk_blocked"
                result["error"] = risk_check["reason"]
                await self.telegram.send_message(
                    f"[RISK] Blocked {signal.signal_type.value} {signal.symbol}: "
                    f"{risk_check['reason']}"
                )
                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "REJECT",
                    "amount_sol": 0,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": self.wallet.public_key,
                    "notes": f"SOL risk blocked: {risk_check['reason']}",
                    "strategy": strategy_label,
                    "reason": TradeReason.RISK_REJECT,
                })
                return result
            # Apply risk-capped size
            trade_usd = risk_check["capped_usd"]

            # Calculate actual token quantity purchased
            token_qty = trade_usd / token_price if token_price > 0 else 0

            # ── DRY-RUN SIMULATION MODE (per-alert) ──
            drm = get_dry_run_manager()
            drm.record_signal_received()
            strategy_name = signal.strategy or "unknown"
            token_symbol_dr = signal.symbol.replace("USDT", "").replace("USD", "")
            tf_dr = signal.timeframe or ""

            if drm.is_dry_run(strategy_name, token_symbol_dr, tf_dr):
                # Calculate TP/SL for simulation (strategy-aware)
                sim_tp = None
                sim_sl = None
                if signal.atr and signal.atr > 0:
                    tp_mult, sl_mult = self._get_strategy_tp_sl(signal.strategy, signal.symbol, signal.timeframe)
                    sim_tp = token_price + (signal.atr * tp_mult)
                    sim_sl = token_price - (signal.atr * sl_mult)

                sim_entry = drm.log_simulated_trade(
                    strategy=strategy_name,
                    token=token_symbol_dr,
                    timeframe=tf_dr,
                    signal_type=signal.signal_type.value,
                    entry_price=token_price,
                    trade_usd=trade_usd,
                    confidence=signal.confidence_score,
                    atr=signal.atr,
                    tp_price=sim_tp,
                    sl_price=sim_sl,
                    claude_decision=claude_resp.decision.value,
                    claude_reasoning=claude_resp.reasoning,
                )

                result["status"] = "dry_run"
                result["dry_run"] = sim_entry

                await self.telegram.send_message(
                    f"[DRY-RUN] {signal.signal_type.value} {signal.symbol} "
                    f"via {strategy_name} {tf_dr}\n"
                    f"WOULD EXECUTE: ${trade_usd:.2f} @ ${token_price:.4f}\n"
                    f"TP: ${sim_tp:.4f if sim_tp else 0} | SL: ${sim_sl:.4f if sim_sl else 0}\n"
                    f"R:R: {sim_entry.get('expected_rr', '?')} | "
                    f"Projected: ${sim_entry.get('simulated_pnl', 0):.2f}\n"
                    f"Cumulative sim P&L: ${drm.get_status()['simulated_pnl']:.2f}"
                )

                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "DRY_RUN",
                    "amount_sol": token_qty,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": "dry_run",
                    "notes": f"Sim via {strategy_name} {tf_dr} | P&L: ${sim_entry.get('simulated_pnl', 0):.2f}",
                    "strategy": strategy_label,
                    "reason": TradeReason.DRY_RUN,
                })
                return result

            # ── PAPER TRADING MODE ──
            paper_trader = get_paper_trader()
            if paper_trader.enabled:
                if signal.signal_type.value in ("CLOSE", "SELL"):
                    paper_result = paper_trader.close_paper_position(
                        signal.symbol, token_price, reason="signal"
                    )
                else:
                    paper_result = paper_trader.execute_paper_trade(
                        signal=signal,
                        decision=result["decision"],
                        token_price=token_price,
                        trade_amount_usd=trade_usd,
                    )

                result["status"] = paper_result.get("status", "paper_executed")
                result["paper"] = paper_result

                # Telegram notification with [PAPER] prefix
                await self.telegram.send_message(
                    f"[PAPER] {signal.signal_type.value} {signal.symbol}\n"
                    f"Amount: ${trade_usd:.2f}\n"
                    f"Price: ${token_price:.4f}\n"
                    f"P&L: ${paper_result.get('pnl_usd', 0):.2f}\n"
                    f"Balance: ${paper_result.get('balance_after', 0):.2f}"
                )

                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "PAPER",
                    "amount_sol": token_qty,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": "paper",
                    "notes": f"Paper trade: {paper_result.get('status', '')}",
                    "strategy": strategy_label,
                    "reason": TradeReason.PAPER,
                })
                return result

            if signal.signal_type.value in ("CLOSE", "SELL"):
                # Long-only bot: SELL means close the long (same path as CLOSE).
                # Previously SELL bypassed position-close logic and just sized a partial
                # swap from portfolio %, leaving positions.status='open' — orphaned the
                # position record and stranded residual tokens in the wallet.
                action_label = signal.signal_type.value
                strategy_name = signal.strategy or ""
                matched_pos = get_open_position_for_signal(signal.symbol, strategy_name)

                if not matched_pos:
                    # ~92% of CLOSE signals land here — Pine indicators fire CLOSE on
                    # every bar where exit-condition is true, even when no position is
                    # open. Log at DEBUG and skip Telegram; periodic summary via _bump_close_filter.
                    logger.debug(
                        f"{action_label} signal for {signal.symbol} from strategy '{strategy_name}' "
                        f"but no matching open position found — ignoring"
                    )
                    _bump_close_filter("ignored")
                    result["status"] = "no_position"
                    result["error"] = (
                        f"No open position for {signal.symbol} from strategy '{strategy_name}'"
                    )
                    return result

                logger.info(
                    f"CLOSE signal matched position #{matched_pos['id']} "
                    f"({signal.symbol} via {strategy_name})"
                )

                # ── Churn guards ─────────────────────────────────────────────
                # Root cause of Apr 18 breakeven losses: indicators fired CLOSE on
                # the same bar as BUY (short_exit bug). That's fixed in Pine, but
                # belt-and-suspenders here protects against 1-2 bar whipsaws and
                # pure fee churn. SL/TP still fire via position_monitor regardless
                # of these guards — only signal-driven closes are gated.
                close_cfg = get("close_guards") or {}
                min_hold_seconds = int(close_cfg.get("min_hold_seconds", 120))
                min_move_pct = float(close_cfg.get("min_move_pct_to_close", 0.005))  # 0.5%

                entry_price = float(matched_pos.get("entry_price") or 0)
                created_at_str = matched_pos.get("created_at") or ""
                try:
                    opened_ts = datetime.fromisoformat(created_at_str.replace("Z", "")).timestamp()
                except Exception:
                    opened_ts = 0.0
                age_seconds = time.time() - opened_ts if opened_ts else 999999

                if age_seconds < min_hold_seconds:
                    logger.debug(
                        f"CLOSE rejected for {signal.symbol} pos #{matched_pos['id']}: "
                        f"only {age_seconds:.0f}s old (min {min_hold_seconds}s) — likely whipsaw"
                    )
                    _bump_close_filter("blocked_too_new")
                    result["status"] = "close_rejected_too_new"
                    return result

                move_pct = abs(token_price - entry_price) / entry_price if entry_price else 0
                if move_pct < min_move_pct:
                    logger.debug(
                        f"CLOSE rejected for {signal.symbol} pos #{matched_pos['id']}: "
                        f"price moved only {move_pct*100:.2f}% from entry "
                        f"${entry_price:.6f} → ${token_price:.6f} (need {min_move_pct*100:.2f}% to clear fees)"
                    )
                    _bump_close_filter("blocked_low_move")
                    result["status"] = "close_rejected_below_fee_threshold"
                    return result

                # Close via position monitor for proper swap execution
                from app.services.position_monitor import get_position_monitor
                monitor = get_position_monitor()
                await monitor._close_position(matched_pos, token_price, "signal", jupiter=None)

                result["status"] = "closed"
                insert_trade({
                    "signal_type": action_label,
                    "symbol": signal.symbol,
                    "action": "EXECUTE",
                    "amount_sol": matched_pos.get("amount_sol", token_qty),
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": self.wallet.public_key,
                    "leverage": 1,
                    "notes": f"Strategy-isolated close ({action_label}): {strategy_name} pos #{matched_pos['id']}",
                    "strategy": strategy_label,
                    "reason": TradeReason.SIGNAL_CLOSE,
                })
                return result

            # Withdraw from Kamino if needed (auto-withdraw before trade)
            if self.kamino.enabled and self.kamino.auto_withdraw and kamino_usdc > 0:
                try:
                    logger.info(f"Withdrawing {kamino_usdc:.2f} USDC from Kamino before trade")
                    withdraw_result = await self.kamino.withdraw_all(self.wallet.get_keypair())
                    if withdraw_result.get("success"):
                        await self.telegram.send_message(
                            f"Kamino Withdraw: {kamino_usdc:.2f} USDC withdrawn for trade execution"
                        )
                        await asyncio.sleep(2)  # Wait for tx to finalize
                        self.wallet.invalidate_cache()
                    else:
                        logger.warning(f"Kamino withdraw failed: {withdraw_result.get('error')}")
                except Exception as e:
                    logger.warning(f"Kamino withdraw error (continuing with available balance): {e}")

            # Resolve target token mint address
            target_mint = self._resolve_token_mint(token_symbol)

            # Execute swap via Jupiter
            if signal.signal_type.value == "BUY":
                # BUY: swap USDC → target token
                input_mint = self.jupiter.usdc_mint
                output_mint = target_mint
                amount_lamports = int(trade_usd * 1_000_000)  # USDC has 6 decimals
            else:
                # SELL: swap target token → USDC
                input_mint = target_mint
                output_mint = self.jupiter.usdc_mint
                # For sells, amount is in target token's smallest unit
                # We use trade_usd / token_price to get token amount
                token_amount = trade_usd / token_price if token_price > 0 else 0
                decimals = self._token_decimals(token_symbol)
                amount_lamports = int(token_amount * (10 ** decimals))

            logger.info(
                f"Executing {signal.signal_type.value} {token_symbol}: "
                f"${trade_usd:.2f} USDC at {leverage}x "
                f"(swap {input_mint[:8]}..→{output_mint[:8]}..)"
            )

            swap_result = await self.jupiter.execute_swap(
                keypair=self.wallet.get_keypair(),
                input_mint=input_mint,
                output_mint=output_mint,
                amount_lamports=amount_lamports,
            )

            result["status"] = "executed"
            result["tx_signature"] = swap_result["tx_signature"]

            # Record trade in SOL risk manager for exposure tracking
            if signal.signal_type.value == "BUY":
                sol_rm.record_trade(token_symbol, trade_usd)

            # Invalidate cache so next balance read is fresh
            self.wallet.invalidate_cache()

            # Get new balance
            new_balance = await self.wallet.get_balance_sol()

            # Log trade
            insert_trade({
                "timestamp": datetime.utcnow().isoformat(),
                "tx_id": swap_result["tx_signature"],
                "signal_type": signal.signal_type.value,
                "symbol": signal.symbol,
                "action": "EXECUTE",
                "amount_sol": token_qty,
                "amount_usd": trade_usd,
                "price_usd": token_price,
                "fees_sol": 0.000005,  # Base tx fee
                "leverage": leverage,
                "confidence_score": signal.confidence_score,
                "claude_reasoning": claude_resp.reasoning,
                "wallet_address": self.wallet.public_key,
                "notes": f"Price impact: {swap_result.get('price_impact', '?')}",
                "strategy": strategy_label,
                "reason": TradeReason.WEBHOOK,
            })

            # Notify Telegram
            await self.telegram.notify_trade_executed(
                tx_sig=swap_result["tx_signature"],
                action=signal.signal_type.value,
                amount_sol=token_qty,
                price_usd=token_price,
                fees_sol=0.000005,
                new_balance_sol=new_balance,
                symbol=signal.symbol,
                trade_usd=trade_usd,
            )

            # Create position record for TP/SL monitoring (BUY only)
            if signal.signal_type.value == "BUY" and signal.atr and signal.atr > 0:
                tp_mult, sl_mult = self._get_strategy_tp_sl(signal.strategy, signal.symbol, signal.timeframe)
                tp_price = token_price + (signal.atr * tp_mult)
                sl_price = token_price - (signal.atr * sl_mult)

                risk_cfg = get("risk")
                max_positions = risk_cfg.get("max_open_positions", 3)
                open_count = get_position_count("open")

                if open_count < max_positions:
                    pos_id = insert_position({
                        "symbol": signal.symbol,
                        "direction": "long",
                        "strategy": signal.strategy or "",
                        "entry_price": token_price,
                        "amount_sol": token_qty,
                        "amount_usdc": trade_usd,
                        "tp_price": tp_price,
                        "sl_price": sl_price,
                        "entry_tx": swap_result["tx_signature"],
                        "timeframe": signal.timeframe or "",
                        "confidence": signal.confidence_score,
                        "atr": signal.atr,
                        "notes": f"TP=${tp_price:.2f} SL=${sl_price:.2f} ATR={signal.atr:.4f}",
                    })
                    logger.info(
                        f"Position #{pos_id} opened: {token_qty:.4f} {token_symbol} @ ${token_price:.4f}, "
                        f"TP=${tp_price:.4f}, SL=${sl_price:.4f}"
                    )
                else:
                    logger.warning(f"Max open positions ({max_positions}) reached, skipping position tracking")
            elif signal.signal_type.value == "BUY":
                logger.warning("No ATR in signal, cannot set TP/SL for position tracking")

            # Auto-deposit idle USDC back to Kamino after trade
            if self.kamino.enabled and self.kamino.auto_deposit:
                try:
                    await asyncio.sleep(3)  # Wait for balances to settle
                    usdc_balance = await self.wallet.get_usdc_balance()
                    deposit_result = await self.kamino.deposit_idle(self.wallet.get_keypair(), usdc_balance)
                    if deposit_result.get("success"):
                        deposited = deposit_result["amount_usdc"]
                        await self.telegram.send_message(
                            f"Kamino Deposit: {deposited:.2f} USDC deposited to earn yield"
                        )
                except Exception as e:
                    logger.warning(f"Kamino auto-deposit after trade failed: {e}")

            return result

        except Exception as e:
            logger.exception(f"Trade engine error: {e}")
            result["status"] = "error"
            result["error"] = str(e)
            await self.telegram.notify_error(str(e), f"Signal: {signal.signal_type.value} {signal.symbol}")
            return result

    # Well-known Solana token mints
    _KNOWN_MINTS = {
        "SOL": "So11111111111111111111111111111111111111112",
        "USDC": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        "JTO": "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
        "WIF": "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
        "BONK": "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
        "PYTH": "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
        "RAY": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        "ETH": "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
        "ORCA": "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE",
        "RENDER": "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof",
        "W": "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
        "DOG": "dog1viwbb2vWDpER5FrJ4YFG6gq6XuyFohUe9TXN65u",
        "JUP": "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        "PENGU": "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
        "FARTCOIN": "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
        "POPCAT": "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
        "MEW": "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",
        "PNUT": "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
        "MOODENG": "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
        "HNT": "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux",
        "DRIFT": "DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7",
        "TNSR": "TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6",
    }

    _TOKEN_DECIMALS = {
        "SOL": 9, "USDC": 6, "JTO": 9, "WIF": 6,
        "BONK": 5, "PYTH": 6, "RAY": 6, "ETH": 8, "ORCA": 6,
        "RENDER": 8, "W": 6, "DOG": 5,
        "JUP": 6, "PENGU": 6, "FARTCOIN": 6, "POPCAT": 9,
        "MEW": 5, "PNUT": 6, "MOODENG": 6,
        "HNT": 8, "DRIFT": 6, "TNSR": 9,
    }

    def _resolve_token_mint(self, symbol: str) -> str:
        """Resolve token symbol to Solana mint address."""
        # Check well-known mints first, then rebalancer config
        if symbol in self._KNOWN_MINTS:
            return self._KNOWN_MINTS[symbol]
        rebal_cfg = get("rebalancer") or {}
        token_mints = rebal_cfg.get("token_mints", {})
        if symbol in token_mints:
            return token_mints[symbol]
        # Fallback to SOL mint if unknown
        logger.warning(f"Unknown token mint for {symbol}, falling back to SOL")
        return self._KNOWN_MINTS["SOL"]

    def _token_decimals(self, symbol: str) -> int:
        """Get decimal places for a token (for lamport conversion)."""
        return self._TOKEN_DECIMALS.get(symbol, 9)

    @staticmethod
    def _get_strategy_tp_sl(
        strategy: Optional[str],
        symbol: Optional[str] = None,
        timeframe: Optional[str] = None,
    ) -> tuple[float, float]:
        """Get TP/SL multipliers for a strategy/token/TF, falling back to global defaults.

        Precedence (highest first):
          1. strategy_token_tf_overrides[strategy][token][tf] — from tp_sl_sweep winners
          2. position_monitor.token_overrides[token].sl_multiplier — manual SL widening
          3. strategy_profiles[strategy] — hand-tuned per-strategy defaults
          4. position_monitor.{tp_multiplier, sl_multiplier} — global defaults
        """
        pos_cfg = get("position_monitor") or {}
        default_tp = pos_cfg.get("tp_multiplier", 4.0)
        default_sl = pos_cfg.get("sl_multiplier", 1.5)

        tp_mult, sl_mult = default_tp, default_sl

        # Strategy-specific overrides (hand-tuned)
        if strategy:
            strategy_cfg = get("strategy_profiles") or {}
            strategy_upper = strategy.upper()
            for name, profile in strategy_cfg.items():
                if strategy_upper.startswith(name.upper()):
                    tp_mult = profile.get("tp_multiplier", default_tp)
                    sl_mult = profile.get("sl_multiplier", default_sl)
                    break

        # Token-specific SL override (e.g., memecoins need wider stops)
        token_key = None
        if symbol:
            token_key = symbol.upper().replace("USDT", "").replace("USD", "")
            token_overrides = pos_cfg.get("token_overrides") or {}
            override = token_overrides.get(token_key)
            if override and "sl_multiplier" in override:
                sl_mult = override["sl_multiplier"]

        # Sweep-generated per-(strategy, token, tf) overrides — highest precedence.
        # Pine sends "EMA Ribbon v1.0" / "240"; YAML is keyed by "EMA Ribbon" / "4H".
        if strategy and token_key and timeframe:
            sweep = _load_tpsl_overrides()
            strat_norm = _normalize_strategy_name(strategy)
            tf_norm = _normalize_timeframe(timeframe)
            slot = sweep.get(strat_norm, {}).get(token_key, {}).get(tf_norm)
            if slot:
                tp_mult = slot.get("atr_tp_mult", tp_mult)
                sl_mult = slot.get("atr_sl_mult", sl_mult)

        return tp_mult, sl_mult

    async def shutdown(self):
        self._running = False
        await self.jupiter.close()
        await self.wallet.close()
        await self.telegram.close()
        await self.news.close()
        await self.kamino.close()
