"""Trade engine - orchestrates signal processing, Claude decision, and execution."""

import asyncio
import hashlib
import logging
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

import yaml

from app.config import get
from app.database import insert_trade, get_stats, log_signal, update_signal_disposition, insert_position, get_position_count, get_open_position_for_signal, get_open_positions, TradeReason
from app.models import WebhookSignal, ClaudeDecision, ClaudeResponse
from app.services.claude_decision import get_claude_decision
from app.services.jupiter_client import JupiterClient
from app.services.news_service import NewsService
from app.services.kamino_client import KaminoClient
from app.services.confluence_filter import get_confluence_filter
from app.services.dry_run_manager import get_dry_run_manager
from app.services.sol_risk_manager import get_sol_risk_manager
from app.services.paper_trading import get_paper_trader
from app.services.telegram_service import TelegramService
from app.services.wallet_service import WalletService

logger = logging.getLogger("bot.engine")

# Duplicate signal detection
_recent_signals: dict[str, float] = {}

# CLOSE-signal filter counters — most CLOSEs (~92%) have no matching position
# (Pine indicators emit CLOSE on every bar where exit-condition is true). The
# bot already drops them correctly; this counter lets us track filter volume
# without spamming logs/Telegram on each one.
_close_filter_stats = {
    "ignored": 0,           # CLOSE arrived but no open position matches
    "blocked_too_new": 0,   # matched but position younger than min_hold_seconds
    "blocked_low_move": 0,  # matched but price hasn't moved enough to clear fees
    "ignored_by_config": 0, # webhook.ignore_close_signals=true blanket drop
    "last_summary_total": 0,
}
_CLOSE_FILTER_SUMMARY_EVERY = 25  # emit summary INFO line every N filtered signals


def _bump_close_filter(reason: str) -> None:
    """Increment a CLOSE-filter counter and emit a summary line every N events."""
    if reason in _close_filter_stats:
        _close_filter_stats[reason] += 1
    total = (
        _close_filter_stats["ignored"]
        + _close_filter_stats["blocked_too_new"]
        + _close_filter_stats["blocked_low_move"]
        + _close_filter_stats["ignored_by_config"]
    )
    if total - _close_filter_stats["last_summary_total"] >= _CLOSE_FILTER_SUMMARY_EVERY:
        logger.info(
            f"CLOSE filter summary (since startup): "
            f"{_close_filter_stats['ignored']} ignored (no position), "
            f"{_close_filter_stats['blocked_too_new']} blocked (too new), "
            f"{_close_filter_stats['blocked_low_move']} blocked (low move), "
            f"{_close_filter_stats['ignored_by_config']} ignored by config"
        )
        _close_filter_stats["last_summary_total"] = total


# ── TP/SL sweep overrides (config_tpsl_overrides.yaml) ───────────────────────
_TPSL_OVERRIDES_PATH = Path(__file__).resolve().parents[2] / "config_tpsl_overrides.yaml"
_tpsl_overrides_cache: dict = {}
_tpsl_overrides_mtime: float = 0.0


def _load_tpsl_overrides() -> dict:
    """Load strategy_token_tf_overrides from config_tpsl_overrides.yaml with mtime caching.

    Returns shape: {strategy: {token: {tf: {atr_sl_mult, atr_tp_mult}}}}
    Returns {} if the file doesn't exist or fails to parse.
    """
    global _tpsl_overrides_cache, _tpsl_overrides_mtime
    try:
        mtime = os.path.getmtime(_TPSL_OVERRIDES_PATH)
    except OSError:
        if _tpsl_overrides_cache:
            _tpsl_overrides_cache = {}
            _tpsl_overrides_mtime = 0.0
        return {}

    if mtime == _tpsl_overrides_mtime:
        return _tpsl_overrides_cache

    try:
        with open(_TPSL_OVERRIDES_PATH) as f:
            data = yaml.safe_load(f) or {}
        _tpsl_overrides_cache = data.get("strategy_token_tf_overrides", {}) or {}
        _tpsl_overrides_mtime = mtime
        logger.info(f"Loaded TP/SL sweep overrides: {sum(len(t) for t in _tpsl_overrides_cache.values())} token slots")
    except Exception as e:
        logger.warning(f"Failed to load {_TPSL_OVERRIDES_PATH}: {e}")
        _tpsl_overrides_cache = {}
        _tpsl_overrides_mtime = mtime  # don't retry until file changes
    return _tpsl_overrides_cache


# ── Tiered position sizing overrides (config_sizing_overrides.yaml) ──────────
# Seeded & regenerated by backtesting/nightly.py write_sizing_overrides().
_SIZING_OVERRIDES_PATH = Path(__file__).resolve().parents[2] / "config_sizing_overrides.yaml"
_sizing_overrides_cache: dict = {}
_sizing_overrides_mtime: float = 0.0


def _load_sizing_overrides() -> dict:
    """Load strategy_token_tf_sizes from config_sizing_overrides.yaml with mtime caching.

    Returns shape: {strategy: {token: {tf: {tier, size_pct, pf, source}}}}
    """
    global _sizing_overrides_cache, _sizing_overrides_mtime
    try:
        mtime = os.path.getmtime(_SIZING_OVERRIDES_PATH)
    except OSError:
        if _sizing_overrides_cache:
            _sizing_overrides_cache = {}
            _sizing_overrides_mtime = 0.0
        return {}

    if mtime == _sizing_overrides_mtime:
        return _sizing_overrides_cache

    try:
        with open(_SIZING_OVERRIDES_PATH) as f:
            data = yaml.safe_load(f) or {}
        _sizing_overrides_cache = data.get("strategy_token_tf_sizes", {}) or {}
        _sizing_overrides_mtime = mtime
        slots = sum(len(tfs) for toks in _sizing_overrides_cache.values() for tfs in toks.values())
        logger.info(f"Loaded sizing tier overrides: {slots} strategy/token/tf slots")
    except Exception as e:
        logger.warning(f"Failed to load {_SIZING_OVERRIDES_PATH}: {e}")
        _sizing_overrides_cache = {}
        _sizing_overrides_mtime = mtime
    return _sizing_overrides_cache


# Map Pine `_strat` string (e.g. "EMA Ribbon v1.0") → backtest canonical name.
# Backtest uses short names; Pine sends full "<Name> v<ver>". Keep explicit — easier to debug than regex.
_STRATEGY_NAME_ALIASES = {
    "ema ribbon": "EMA Ribbon",
    "stoch rsi": "Stoch RSI",
    "fvg": "FVG",
    "vwap dev": "VWAP Dev",
    "vwap deviation": "VWAP Dev",
    "liq sweep": "Liq Sweep",
    "liquidity sweep": "Liq Sweep",
    "donchian": "Donchian",
    "donchian breakout": "Donchian",
    # Bull-roster regime-filtered variants (deployed 2026-05-08).
    # Match nightly.py's STRATEGIES dict short keys so `Donch+ADX`/`EMA+ADX`
    # entries in config_sizing_overrides.yaml map cleanly. The detector
    # writes/removes entries under these keys on BULL_CONFIRMED/BULL_LOST.
    "donchian + adx": "Donch+ADX",
    "ema ribbon + adx": "EMA+ADX",
}


def _normalize_strategy_name(raw: Optional[str]) -> Optional[str]:
    """'EMA Ribbon v1.0' → 'EMA Ribbon'. Returns None if no match."""
    if not raw:
        return None
    # Strip trailing " v<digits>..." version tag
    base = raw.strip()
    for tag_sep in (" v", " V"):
        idx = base.rfind(tag_sep)
        if idx > 0 and idx < len(base) - 1 and base[idx + 2].isdigit():
            base = base[:idx]
            break
    return _STRATEGY_NAME_ALIASES.get(base.lower(), base)


# Pine `timeframe.period` emits raw resolution codes. Backtest uses human labels.
_TIMEFRAME_ALIASES = {
    "15": "15m", "15m": "15m",
    "60": "1H",  "1h": "1H", "1H": "1H",
    "240": "4H", "4h": "4H", "4H": "4H",
    "D": "1D",   "1D": "1D", "1d": "1D",
}


def _normalize_timeframe(raw: Optional[str]) -> Optional[str]:
    """'240' → '4H', '60' → '1H'. Returns input unchanged if not mapped."""
    if not raw:
        return None
    return _TIMEFRAME_ALIASES.get(raw.strip(), raw)


def get_sizing_override(strategy: Optional[str], symbol: Optional[str],
                        timeframe: Optional[str]) -> Optional[dict]:
    """Look up tier sizing for this (strategy, token, tf). Returns {tier, size_pct, pf} or None."""
    strat = _normalize_strategy_name(strategy)
    tf = _normalize_timeframe(timeframe)
    if not (strat and symbol and tf):
        return None
    token = symbol.upper().replace("USDT", "").replace("USD", "").replace(".P", "")
    slot = _load_sizing_overrides().get(strat, {}).get(token, {}).get(tf)
    if not slot:
        return None
    return slot


def _strip_pair(symbol: str) -> str:
    """Normalise 'BONKUSDT' → 'BONK' for correlation lookups."""
    return symbol.upper().replace("USDT", "").replace("USD", "").replace(".P", "")


def correlation_check(symbol: str) -> Optional[dict]:
    """Check if opening a new long in `symbol` would exceed its correlation group cap.

    Returns None if allowed, or a dict {group, limit, held: [tokens]} if blocked.
    """
    cfg = get("correlation") or {}
    if not cfg.get("enabled"):
        return None
    groups = cfg.get("groups") or {}

    tok = _strip_pair(symbol)
    # Find which group this token belongs to (first match wins)
    group_name = None
    group_cfg = None
    for gname, gcfg in groups.items():
        if tok in {t.upper() for t in (gcfg.get("tokens") or [])}:
            group_name = gname
            group_cfg = gcfg
            break
    if group_name is None:
        return None  # untracked token, no cap

    limit = int(group_cfg.get("max_concurrent", 99))
    members = {t.upper() for t in (group_cfg.get("tokens") or [])}
    held = [
        _strip_pair(p.get("symbol", ""))
        for p in get_open_positions()
        if _strip_pair(p.get("symbol", "")) in members
    ]
    # Don't double-count: if an open position already exists on the same symbol,
    # this BUY is likely a pyramid/add — let Claude + risk manager handle that,
    # correlation cap only applies to *new* distinct symbols.
    distinct_held = set(held) - {tok}
    if len(distinct_held) >= limit:
        return {
            "group": group_name,
            "limit": limit,
            "held": sorted(distinct_held),
            "token": tok,
        }
    return None


# =============================================================================
# SIGNAL PRIORITY QUEUE
# =============================================================================

class SignalQueue:
    """Batches simultaneous signals and processes highest confidence first.

    When multiple alerts fire on the same candle close (e.g., 3 tokens on 4H),
    they arrive within seconds. This queue collects them in a short window,
    then processes in confidence-descending order, checking budget before each.

    The webhook returns immediately (fire-and-forget) so TradingView doesn't
    timeout. Processing results are sent via Telegram notifications.
    """

    def __init__(self):
        self._queue: list[tuple[WebhookSignal, str]] = []  # (signal, source_ip)
        self._lock = asyncio.Lock()
        self._drain_task: Optional[asyncio.Task] = None

    async def enqueue(self, signal: WebhookSignal, source_ip: str):
        """Add signal to queue. Processing happens after batch window expires."""
        queue_cfg = get("signal_queue") or {}
        enabled = queue_cfg.get("enabled", True)
        batch_window = queue_cfg.get("batch_window_seconds", 5)

        if not enabled:
            # Queue disabled — process immediately (legacy behavior)
            engine = TradeEngine()
            try:
                await engine.process_signal(signal, source_ip)
            finally:
                await engine.shutdown()
            return

        async with self._lock:
            self._queue.append((signal, source_ip))

            # Start drain timer if not already running
            if self._drain_task is None or self._drain_task.done():
                self._drain_task = asyncio.create_task(self._drain_after(batch_window))

    async def _drain_after(self, delay: float):
        """Wait for batch window then process all queued signals."""
        await asyncio.sleep(delay)

        async with self._lock:
            batch = list(self._queue)
            self._queue.clear()

        if not batch:
            return

        # Sort by confidence (highest first)
        batch.sort(key=lambda x: x[0].confidence_score, reverse=True)

        logger.info(
            f"Signal queue draining {len(batch)} signals: "
            + ", ".join(f"{s.symbol}({s.confidence_score})" for s, _ in batch)
        )

        # Notify if multiple signals batched
        if len(batch) > 1:
            engine = TradeEngine()
            order_str = " > ".join(
                f"{s.symbol} {s.timeframe or '?'} (conf:{s.confidence_score})"
                for s, _ in batch
            )
            await engine.telegram.send_message(
                f"Signal Queue: {len(batch)} simultaneous signals\n"
                f"Priority order: {order_str}"
            )
            await engine.shutdown()

        # Process in priority order
        for signal, source_ip in batch:
            engine = TradeEngine()
            try:
                # Check position limit before processing
                risk_cfg = get("risk")
                max_positions = risk_cfg.get("max_open_positions", 3)
                open_count = get_position_count("open")
                if open_count >= max_positions and signal.signal_type.value == "BUY":
                    logger.warning(
                        f"Skipping {signal.symbol} (conf:{signal.confidence_score}) — "
                        f"max positions reached after higher-priority trades"
                    )
                    update_signal_disposition(
                        signal.signal_log_id, "skipped_max_positions",
                        reason=f"{open_count}/{max_positions} open positions cap reached",
                    )
                    await engine.telegram.send_message(
                        f"Signal Queue: SKIPPED {signal.symbol} {signal.timeframe or ''} "
                        f"(conf:{signal.confidence_score}) — max positions reached"
                    )
                elif signal.signal_type.value == "BUY" and (corr := correlation_check(signal.symbol)):
                    logger.warning(
                        f"Skipping {signal.symbol} — correlation cap ({corr['group']} "
                        f"{len(corr['held'])}/{corr['limit']})"
                    )
                    update_signal_disposition(
                        signal.signal_log_id, "skipped_correlation",
                        reason=f"{corr['group']} cap {len(corr['held'])}/{corr['limit']} (held: {','.join(corr['held'][:3])})",
                    )
                    await engine.telegram.send_message(
                        f"Signal Queue: SKIPPED {signal.symbol} — correlation cap "
                        f"({corr['group']} {len(corr['held'])}/{corr['limit']})"
                    )
                else:
                    await engine.process_signal(signal, source_ip)
            except Exception as e:
                logger.error(f"Signal queue processing error for {signal.symbol}: {e}")
            finally:
                await engine.shutdown()


# Singleton queue
_signal_queue: Optional[SignalQueue] = None


async def _confluence_timeout_handler(signal: WebhookSignal, source_ip: str):
    """Called when confluence timeout fires with on_timeout='execute'."""
    engine = TradeEngine()
    try:
        await engine.process_signal(signal, source_ip)
    finally:
        await engine.shutdown()


def get_signal_queue() -> SignalQueue:
    global _signal_queue
    if _signal_queue is None:
        _signal_queue = SignalQueue()
        # Wire confluence timeout callback
        from app.services.confluence_filter import get_confluence_filter
        cf = get_confluence_filter()
        cf.set_confirmed_callback(_confluence_timeout_handler)
    return _signal_queue


# Known Solana program "Custom" error decode for friendlier swap-failure
# summaries. Keep small — the goal is "tell the user what kind of failure"
# not "decode every Anchor enum". Add entries as we learn.
_SOLANA_CUSTOM_ERRORS = {
    29: "InvalidInput / pool state stale (Raydium AMM rejected — likely slippage exceeded mid-block)",
    1:  "InvalidArgument",
    6:  "Slippage tolerance exceeded",
    24: "InsufficientFunds",
}


def _summarize_swap_error(err_text: str) -> str:
    """Pull a short, actionable reason out of a Solana/EVM swap error blob.

    Solana RPC errors often include 4KB+ of program logs. We only want the
    actionable bit — what failed and why. Returns ≤300 chars.
    """
    import re

    # Look for Solana custom program errors first (most common case)
    # Format: "custom program error: 0xNN" or "Custom: NN"
    m = re.search(r"['\"]?Custom['\"]?\s*:\s*(\d+)", err_text)
    if not m:
        m = re.search(r"custom program error:\s*0x([0-9a-fA-F]+)", err_text)
        if m:
            code = int(m.group(1), 16)
        else:
            code = None
    else:
        code = int(m.group(1))

    # Try to find which program failed
    prog_match = re.search(r"Program (\w{32,44}) failed", err_text)
    failed_program = prog_match.group(1) if prog_match else None

    if code is not None:
        decoded = _SOLANA_CUSTOM_ERRORS.get(code, f"Custom error {code}")
        out = f"DEX rejected swap: {decoded}"
        if failed_program:
            out += f" (program {failed_program[:8]}…)"
        return out[:300]

    # EVM revert
    if "swap reverted" in err_text:
        m = re.search(r"tx=(\w+)", err_text)
        return f"EVM swap reverted on-chain. Tx: {m.group(1) if m else 'unknown'}"[:300]

    # OpenOcean
    if "OpenOcean" in err_text:
        m = re.search(r"OpenOcean[^:]*:\s*(.{0,200})", err_text)
        return f"OpenOcean error: {m.group(1) if m else err_text[:200]}"[:300]

    # Generic Transaction failed — first 250 chars after the marker
    m = re.search(r"Transaction failed[^:]*:\s*(.{0,250})", err_text)
    if m:
        return f"Transaction failed: {m.group(1).strip()}"[:300]

    # Last resort
    return err_text[:300]


class TradeEngine:
    """Main trade orchestration engine."""

    def __init__(self):
        self.jupiter = JupiterClient()
        self.wallet = WalletService()
        self.telegram = TelegramService()
        self.news = NewsService()
        self.kamino = KaminoClient()
        # EVM execution lane (Phase 3) — lazy-initialized on first EVM trade.
        # Skipping init here so the bot still runs even if evm_wallet config
        # block is missing or the EVM wallet is unfunded.
        self._evm_wallet = None
        self._evm_executor = None
        self._binance_us = None  # Phase 2 (2026-05-09) — lazy-init Binance.US client
        self._running = True

    # ── EVM execution lane (Phase 3) ─────────────────────────────────────────
    # Symbols that route to the EVM (Arbitrum) execution path instead of
    # Jupiter on Solana. INJ is the only WF passer requiring EVM as of
    # 2026-05-02; others are research-only until they cross WF thresholds.
    EVM_TOKENS = {
        # symbol → (Arbitrum ERC20 contract, decimals)
        # INJ removed 2026-05-08 — Phase 4 audit found canonical Injective token
        # has ZERO Arbitrum liquidity (only Ethereum mainnet pools exist). Old
        # registry address 0x97ad75… was bogus. Liq Sweep / INJ.P alert culled.
        # Validated 2026-05-08 via dry-run swap (Phase 4):
        "UNI":   ("0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0", 18),  # ✓
        "ARB":   ("0x912CE59144191C1204E64559FE8253a0e49E6548", 18),  # ✓
        # Near-misses pre-mapped in case they cross WF later (UNVERIFIED):
        "LDO":   ("0x13Ad51ed4F1B7e9Dc168d8a00cB3f4dDD85EfA60", 18),
        "COMP":  ("0x354A6dA3fcde098F8389cad84b0182725c6C91dE", 18),
        "AAVE":  ("0xba5DdD1f9d7F570dc94a51479a000E3BCE967196", 18),
        "LINK":  ("0xf97f4df75117a78c1A5a0DBb814Af92458539FB4", 18),
    }
    EVM_USDC_CONTRACT = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    EVM_USDC_DECIMALS = 6

    # ── Binance.US execution lane (Phase 2, 2026-05-09) ──────────────────
    # Symbols that route to the Binance.US CEX instead of Solana/EVM DEX.
    #
    # Initial roster (added after exchangeInfo probe 2026-05-09):
    # - FLOKI: bull-roster combos that were "deferred" to BSC chain extension —
    #   FLOKI is on Binance.US ($5171 max market order) so we can now run
    #   Donch+ADX/FLOKI (PF 2.31) and Liq Sweep/FLOKI (PF 1.45) without
    #   building BSC support.
    #
    # NOT included:
    # - INJ: not listed on Binance.US (US regulatory). Liq Sweep/INJ/4H
    #   remains executable only if we build a Cosmos lane (Keplr/Helix).
    # - KAVA: listed but MARKET_LOT_SIZE caps single market order at $2.56,
    #   below any meaningful Phase 6 trade size. Limit orders could work
    #   but we don't have that path yet. Mean Rev/KAVA stays untradeable.
    # - MOODENG: also has tight $2.42 cap. Currently routes through Solana.
    #
    # The value is the Binance.US trading symbol (USDT-quoted by default).
    BINANCE_TOKENS = {
        "FLOKI": "FLOKIUSDT",
        # 2026-05-12: BTC/DOGE/OP have deployed 1D alerts (Donchian, Stoch RSI)
        # but were absent from this registry — a BUY signal would have routed
        # to Solana → JupiterClient.get_token_price → "Unknown token" → silent
        # drop. Caught by the integration smoke test before any real fire.
        # All three are listed on Binance.US with healthy market depth.
        "BTC":   "BTCUSDT",
        "DOGE":  "DOGEUSDT",
        "OP":    "OPUSDT",
    }

    def _is_evm_symbol(self, symbol: str) -> bool:
        """Return True if the given token symbol routes to EVM execution."""
        return symbol.upper() in self.EVM_TOKENS

    def _is_binance_symbol(self, symbol: str) -> bool:
        """Return True if the given token symbol routes to Binance.US CEX."""
        # Match precedence: EVM > Binance — a symbol mapped to EVM stays there
        # to avoid double-execution. Move out of EVM_TOKENS first if you want
        # to migrate it to Binance.
        if self._is_evm_symbol(symbol):
            return False
        return symbol.upper() in self.BINANCE_TOKENS

    def _get_evm_wallet(self):
        """Lazy-init the EVM wallet on first use. Raises if config missing."""
        if self._evm_wallet is None:
            from app.services.evm_wallet_service import EVMWalletService
            self._evm_wallet = EVMWalletService()
        return self._evm_wallet

    def _get_evm_executor(self):
        """Lazy-init the EVM swap executor on first use."""
        if self._evm_executor is None:
            from app.services.evm_swap_executor import EVMSwapExecutor
            self._evm_executor = EVMSwapExecutor(self._get_evm_wallet())
        return self._evm_executor

    def _get_binance_us(self):
        """Lazy-init the Binance.US client on first use."""
        if self._binance_us is None:
            from app.services.binance_us_client import BinanceUSClient
            self._binance_us = BinanceUSClient()
        return self._binance_us

    def is_duplicate(self, signal: WebhookSignal) -> bool:
        """Check if this signal is a duplicate within the configured window."""
        window = get("webhook", "duplicate_window_seconds", 30)
        sig_hash = hashlib.sha256(
            f"{signal.signal_type}:{signal.symbol}:{signal.entry_price_estimate}".encode()
        ).hexdigest()[:16]

        now = time.time()
        # Clean old entries
        expired = [k for k, v in _recent_signals.items() if now - v > window]
        for k in expired:
            del _recent_signals[k]

        if sig_hash in _recent_signals:
            logger.warning(f"Duplicate signal detected: {sig_hash}")
            return True

        _recent_signals[sig_hash] = now
        return False

    async def process_signal(self, signal: WebhookSignal, source_ip: str = "") -> dict:
        """Full signal processing pipeline."""
        result = {
            "status": "pending",
            "signal_type": signal.signal_type.value,
            "decision": None,
            "tx_signature": None,
            "error": None,
        }

        try:
            # Strategy name from indicator webhook (e.g. "FVG v1.0")
            strategy_label = signal.strategy or ""

            # 1. Persist signal — webhook handler already INSERTed signals_log
            # with disposition='received' (2026-05-13 audit-trail fix). For
            # programmatic invocations (no webhook origin), fall back to
            # log_signal here so we still capture the event.
            if not getattr(signal, "signal_log_id", None):
                signal.signal_log_id = log_signal(signal.model_dump_json(), source_ip)

            # 1a. Blanket CLOSE filter — webhook.ignore_close_signals is the
            # tier-0 drop. Audit 2026-05-10 showed indicator CLOSEs closed
            # positions at +1.4% avg vs +8.0% TP avg — they're too eager.
            # Exits now flow only through TP/SL/trailing-stop in position_monitor.
            # This filter runs BEFORE duplicate detection and any heavy work
            # (Telegram, Claude, market data) so spam is dropped cheaply.
            if (signal.signal_type.value == "CLOSE"
                    and bool(get("webhook", "ignore_close_signals", False))):
                _bump_close_filter("ignored_by_config")
                logger.debug(
                    f"CLOSE ignored by config: {signal.symbol} "
                    f"(strategy={strategy_label or '?'}) — "
                    f"exits handled by TP/SL/trail in position_monitor"
                )
                result["status"] = "close_ignored_by_config"
                update_signal_disposition(
                    signal.signal_log_id, "dropped_close_filter",
                    reason="CLOSE signals ignored — exits via TP/SL/trail only",
                )
                return result

            # 2. Check duplicate
            if self.is_duplicate(signal):
                result["status"] = "duplicate"
                result["error"] = "Duplicate signal ignored"
                update_signal_disposition(
                    signal.signal_log_id, "skipped_dedup",
                    reason="duplicate signal within dedup window",
                )
                return result

            # 2.5. Correlation cap — block BUYs that would stack same-group exposure
            if signal.signal_type.value == "BUY":
                corr_block = correlation_check(signal.symbol)
                if corr_block:
                    msg = (
                        f"Correlation cap hit ({corr_block['group']}): "
                        f"holding {len(corr_block['held'])}/{corr_block['limit']} "
                        f"[{', '.join(corr_block['held'])}] — rejecting {corr_block['token']}"
                    )
                    logger.warning(msg)
                    await self.telegram.send_message(f"[CORR] {msg}")
                    insert_trade({
                        "signal_type": signal.signal_type.value,
                        "symbol": signal.symbol,
                        "action": "REJECT",
                        "amount_sol": 0,
                        "price_usd": signal.entry_price_estimate or 0,
                        "confidence_score": signal.confidence_score,
                        "claude_reasoning": "Correlation cap — not queried",
                        "wallet_address": self.wallet.public_key,
                        "notes": f"Correlation: {corr_block['group']} {len(corr_block['held'])}/{corr_block['limit']} held [{', '.join(corr_block['held'])}]",
                        "strategy": strategy_label,
                        "reason": TradeReason.CORRELATION_REJECT,
                    })
                    result["status"] = "correlation_blocked"
                    result["error"] = msg
                    return result

            # 3. Notify Telegram
            await self.telegram.notify_webhook_received(signal.model_dump())

            # 3.5. Confluence filter — hold signal until a second strategy confirms
            cf = get_confluence_filter()
            if cf.enabled:
                confirmed_signal = await cf.check(signal, source_ip)
                if confirmed_signal is None:
                    # Signal is being held — will be processed via timeout callback
                    result["status"] = "confluence_pending"
                    return result
                # Use the confirmed signal (may differ if higher-conf was picked)
                signal = confirmed_signal

            # 4. Gather context for Claude
            sol_price = await self.jupiter.get_sol_price()
            balance_sol = await self.wallet.get_balance_sol()
            usdc_balance = await self.wallet.get_usdc_balance()
            market_data = await self.jupiter.get_market_data()
            headlines = await self.news.get_headlines()

            # Check Kamino deposits (available purchasing power)
            kamino_usdc = 0.0
            if self.kamino.enabled:
                try:
                    kamino_pos = await self.kamino.get_user_position(self.wallet.public_key)
                    if kamino_pos.get("has_position"):
                        kamino_usdc = kamino_pos.get("deposited_usdc", 0.0)
                except Exception as e:
                    logger.warning(f"Could not check Kamino balance: {e}")

            # Resolve token symbol (e.g. FLOKIUSDT → FLOKI). MUST come before
            # any code that uses it — the Phase 2 Binance.US block below used
            # token_symbol before this assignment, throwing UnboundLocalError
            # on every BUY signal (caught 2026-05-10 when FLOKI BUY didn't fire).
            token_symbol = signal.symbol.replace("USDT", "").replace("USD", "").replace(".P", "")

            # Total purchasing power = USDC in wallet + Kamino deposits + SOL value
            sol_usd_value = balance_sol * sol_price
            # Binance.US USDT — only counted when routing to Binance lane to avoid
            # over-sizing Solana/EVM trades that can't access CEX funds. Phase 2
            # added 2026-05-09.
            binance_usdt = 0.0
            if self._is_binance_symbol(token_symbol):
                try:
                    bn = self._get_binance_us()
                    if bn.enabled:
                        binance_usdt = await bn.get_total_usdt_value()
                except Exception as e:
                    logger.warning(f"Binance.US balance fetch failed: {e}")

            # EVM lane funds — only fetched when the trade is actually going to
            # Arbitrum so we don't pay RPC roundtrips on every Solana signal.
            # Aave V3 USDC counts as tradeable since the executor will JIT auto-
            # withdraw before the swap if wallet USDC is short.
            # Bug fix 2026-05-12 LDO: sizing previously omitted EVM lane funds
            # entirely, so an EVM signal arriving right after a Solana BUY drained
            # the shared sizing pool to $0 → swap_quote called with amount=0.
            evm_usdc = 0.0
            evm_aave_usdc = 0.0
            evm_reserve = 0.0
            if self._is_evm_symbol(token_symbol):
                try:
                    evm_w = self._get_evm_wallet()
                    evm_usdc = await evm_w.get_usdc_balance()
                except Exception as e:
                    logger.warning(f"EVM USDC balance fetch failed: {e}")
                try:
                    from app.services.aave_v3_client import AaveV3Client
                    aave = AaveV3Client()
                    if aave.enabled:
                        evm_aave_usdc = await aave.get_supply_balance() or 0.0
                except Exception as e:
                    logger.warning(f"Aave V3 supply balance fetch failed: {e}")
                evm_reserve = float(get("aave_v3", "reserve_usdc", 0.0) or 0.0)

            total_usd = (
                usdc_balance + kamino_usdc + sol_usd_value
                + binance_usdt + evm_usdc + evm_aave_usdc
            )

            # Tradeable USDC is LANE-ISOLATED: a trade can only spend funds on
            # its own execution lane. Pre-fix this unioned Solana + Binance into
            # one pool, which silently undersized cross-lane trades when one
            # lane was depleted by a recent fill. Now each lane sizes against
            # its own pool minus its reserve.
            kamino_cfg = get("kamino") or {}
            usdc_reserve = kamino_cfg.get("reserve_usdc", 0.0)
            if self._is_evm_symbol(token_symbol):
                tradeable_usd = max(0.0, evm_usdc + evm_aave_usdc - evm_reserve)
            elif self._is_binance_symbol(token_symbol):
                tradeable_usd = max(0.0, binance_usdt)
            else:
                tradeable_usd = max(0.0, usdc_balance + kamino_usdc - usdc_reserve)

            # Get actual token price (use Jupiter price lookup, fall back to signal estimate)
            if token_symbol == "SOL":
                token_price = sol_price
            else:
                try:
                    token_price = await self.jupiter.get_token_price(token_symbol)
                except Exception:
                    token_price = signal.entry_price_estimate

            # 5. Check low balance shutdown (based on total USD, not just SOL)
            risk_cfg = get("risk")
            low_bal_usd = risk_cfg.get("low_balance_shutdown_usd", 50.0)
            if total_usd < low_bal_usd:
                result["status"] = "shutdown"
                result["error"] = (
                    f"Total balance too low: ${total_usd:.2f} "
                    f"(SOL: ${sol_usd_value:.2f}, USDC: ${usdc_balance:.2f}, Kamino: ${kamino_usdc:.2f})"
                )
                await self.telegram.notify_error(result["error"], "Low balance shutdown triggered")
                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "REJECT",
                    "amount_sol": 0,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": "Low balance shutdown",
                    "wallet_address": self.wallet.public_key,
                    "notes": f"Automatic shutdown - total ${total_usd:.2f} below ${low_bal_usd:.2f} threshold",
                    "strategy": strategy_label,
                    "reason": TradeReason.LOW_BALANCE,
                })
                update_signal_disposition(
                    signal.signal_log_id, "rejected_low_balance",
                    reason=f"total ${total_usd:.2f} < threshold ${low_bal_usd:.2f}",
                )
                return result

            # 6. Build risk params
            db_stats = get_stats()
            risk_params = {
                "max_purchase_sol": risk_cfg.get("max_purchase_sol", 5.0),
                "max_purchase_usd": risk_cfg.get("max_purchase_usd", 500.0),
                "max_leverage": risk_cfg.get("max_leverage", 5),
                "daily_loss_limit_percent": risk_cfg.get("daily_loss_limit_percent", 10.0),
                "low_balance_shutdown_usd": low_bal_usd,
                "today_pnl_usd": db_stats.get("today_pnl_usd", 0),
                "geo_risk_weight": get("geo_risk", "weight", 0.7),
                # Full balance breakdown for Claude
                "usdc_wallet": usdc_balance,
                "usdc_kamino": kamino_usdc,
                "tradeable_usd": tradeable_usd,
                "total_usd": total_usd,
            }

            # 7. Get Claude decision (skip in dry-run — Claude is slow + costly,
            # not needed to verify pre-execution routing logic).
            if getattr(signal, "dry_run", False):
                # Synthetic accept so downstream sizing/route code still runs
                claude_resp = ClaudeResponse(
                    decision=ClaudeDecision.EXECUTE,
                    reasoning="dry_run synthetic — Claude bypass for pre-flight",
                    risk_score=5,
                )
            else:
                logger.info(
                    f"Requesting Claude decision for {signal.signal_type.value} {signal.symbol} "
                    f"(tradeable: ${tradeable_usd:.2f}, total: ${total_usd:.2f})"
                )
                claude_resp = await get_claude_decision(
                    signal=signal,
                    wallet_balance_sol=balance_sol,
                    wallet_balance_usd=total_usd,
                    sol_price=sol_price,
                    market_data=market_data,
                    news_headlines=headlines,
                    risk_params=risk_params,
                )

            result["decision"] = claude_resp.model_dump()
            await self.telegram.notify_claude_decision(result["decision"], signal.signal_type.value)

            # 8. Execute based on decision
            if claude_resp.decision == ClaudeDecision.REJECT:
                result["status"] = "rejected"
                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "REJECT",
                    "amount_sol": 0,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": self.wallet.public_key,
                    "notes": f"Risk score: {claude_resp.risk_score}",
                    "strategy": strategy_label,
                    "reason": TradeReason.CLAUDE_REJECT,
                })
                _reject_reason = (claude_resp.reasoning or "no reason given")[:160]
                update_signal_disposition(
                    signal.signal_log_id, "rejected_claude",
                    reason=f"Claude REJECT (risk={claude_resp.risk_score}): {_reject_reason}",
                )
                return result

            # Determine trade parameters.
            # Precedence: Claude MODIFY > tiered sizing override > signal default.
            if claude_resp.decision == ClaudeDecision.MODIFY and claude_resp.modified_size_percent:
                size_pct = claude_resp.modified_size_percent
            else:
                tier_slot = get_sizing_override(signal.strategy, signal.symbol, signal.timeframe)
                if tier_slot:
                    size_pct = tier_slot["size_pct"]
                    logger.info(
                        f"Sizing tier {tier_slot['tier']} applied: {signal.strategy}/{signal.symbol}/"
                        f"{signal.timeframe} → {size_pct}% (PF={tier_slot.get('pf', '?')})"
                    )
                else:
                    size_pct = signal.suggested_position_size_percent
            leverage = (
                claude_resp.modified_leverage
                if claude_resp.decision == ClaudeDecision.MODIFY and claude_resp.modified_leverage
                else signal.suggested_leverage
            )

            # Apply risk caps
            leverage = min(leverage, risk_cfg.get("max_leverage", 5))
            size_pct = min(size_pct, risk_cfg.get("max_position_size_percent", 15))

            # Calculate trade amount in USD (base currency is USDC, not SOL)
            trade_usd = tradeable_usd * (size_pct / 100)
            max_purchase_usd = risk_cfg.get("max_purchase_usd", 500.0)
            trade_usd = min(trade_usd, max_purchase_usd)
            # ── SOL RISK MANAGER PRE-TRADE CHECK ──
            sol_rm = get_sol_risk_manager()
            risk_check = sol_rm.check_order(token_symbol, trade_usd, signal.signal_type.value)
            if not risk_check["allowed"]:
                result["status"] = "risk_blocked"
                result["error"] = risk_check["reason"]
                await self.telegram.send_message(
                    f"[RISK] Blocked {signal.signal_type.value} {signal.symbol}: "
                    f"{risk_check['reason']}"
                )
                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "REJECT",
                    "amount_sol": 0,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": self.wallet.public_key,
                    "notes": f"SOL risk blocked: {risk_check['reason']}",
                    "strategy": strategy_label,
                    "reason": TradeReason.RISK_REJECT,
                })
                return result
            # Apply risk-capped size
            trade_usd = risk_check["capped_usd"]

            # Calculate actual token quantity purchased
            token_qty = trade_usd / token_price if token_price > 0 else 0

            # ── DRY-RUN SIMULATION MODE (per-alert) ──
            drm = get_dry_run_manager()
            drm.record_signal_received()
            strategy_name = signal.strategy or "unknown"
            token_symbol_dr = signal.symbol.replace("USDT", "").replace("USD", "").replace(".P", "")
            tf_dr = signal.timeframe or ""

            if drm.is_dry_run(strategy_name, token_symbol_dr, tf_dr):
                # Calculate TP/SL for simulation (strategy-aware)
                sim_tp = None
                sim_sl = None
                if signal.atr and signal.atr > 0:
                    tp_mult, sl_mult = self._get_strategy_tp_sl(signal.strategy, signal.symbol, signal.timeframe)
                    sim_tp = token_price + (signal.atr * tp_mult)
                    sim_sl = token_price - (signal.atr * sl_mult)

                sim_entry = drm.log_simulated_trade(
                    strategy=strategy_name,
                    token=token_symbol_dr,
                    timeframe=tf_dr,
                    signal_type=signal.signal_type.value,
                    entry_price=token_price,
                    trade_usd=trade_usd,
                    confidence=signal.confidence_score,
                    atr=signal.atr,
                    tp_price=sim_tp,
                    sl_price=sim_sl,
                    claude_decision=claude_resp.decision.value,
                    claude_reasoning=claude_resp.reasoning,
                )

                result["status"] = "dry_run"
                result["dry_run"] = sim_entry

                await self.telegram.send_message(
                    f"[DRY-RUN] {signal.signal_type.value} {signal.symbol} "
                    f"via {strategy_name} {tf_dr}\n"
                    f"WOULD EXECUTE: ${trade_usd:.2f} @ ${token_price:.4f}\n"
                    f"TP: ${sim_tp:.4f if sim_tp else 0} | SL: ${sim_sl:.4f if sim_sl else 0}\n"
                    f"R:R: {sim_entry.get('expected_rr', '?')} | "
                    f"Projected: ${sim_entry.get('simulated_pnl', 0):.2f}\n"
                    f"Cumulative sim P&L: ${drm.get_status()['simulated_pnl']:.2f}"
                )

                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "DRY_RUN",
                    "amount_sol": token_qty,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": "dry_run",
                    "notes": f"Sim via {strategy_name} {tf_dr} | P&L: ${sim_entry.get('simulated_pnl', 0):.2f}",
                    "strategy": strategy_label,
                    "reason": TradeReason.DRY_RUN,
                })
                return result

            # ── PAPER TRADING MODE ──
            paper_trader = get_paper_trader()
            if paper_trader.enabled:
                if signal.signal_type.value in ("CLOSE", "SELL"):
                    paper_result = paper_trader.close_paper_position(
                        signal.symbol, token_price, reason="signal"
                    )
                else:
                    paper_result = paper_trader.execute_paper_trade(
                        signal=signal,
                        decision=result["decision"],
                        token_price=token_price,
                        trade_amount_usd=trade_usd,
                    )

                result["status"] = paper_result.get("status", "paper_executed")
                result["paper"] = paper_result

                # Telegram notification with [PAPER] prefix
                await self.telegram.send_message(
                    f"[PAPER] {signal.signal_type.value} {signal.symbol}\n"
                    f"Amount: ${trade_usd:.2f}\n"
                    f"Price: ${token_price:.4f}\n"
                    f"P&L: ${paper_result.get('pnl_usd', 0):.2f}\n"
                    f"Balance: ${paper_result.get('balance_after', 0):.2f}"
                )

                insert_trade({
                    "signal_type": signal.signal_type.value,
                    "symbol": signal.symbol,
                    "action": "PAPER",
                    "amount_sol": token_qty,
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": "paper",
                    "notes": f"Paper trade: {paper_result.get('status', '')}",
                    "strategy": strategy_label,
                    "reason": TradeReason.PAPER,
                })
                return result

            if signal.signal_type.value in ("CLOSE", "SELL"):
                # Long-only bot: SELL means close the long (same path as CLOSE).
                # Previously SELL bypassed position-close logic and just sized a partial
                # swap from portfolio %, leaving positions.status='open' — orphaned the
                # position record and stranded residual tokens in the wallet.
                action_label = signal.signal_type.value
                strategy_name = signal.strategy or ""
                matched_pos = get_open_position_for_signal(signal.symbol, strategy_name)

                if not matched_pos:
                    # ~92% of CLOSE signals land here — Pine indicators fire CLOSE on
                    # every bar where exit-condition is true, even when no position is
                    # open. Log at DEBUG and skip Telegram; periodic summary via _bump_close_filter.
                    logger.debug(
                        f"{action_label} signal for {signal.symbol} from strategy '{strategy_name}' "
                        f"but no matching open position found — ignoring"
                    )
                    _bump_close_filter("ignored")
                    result["status"] = "no_position"
                    result["error"] = (
                        f"No open position for {signal.symbol} from strategy '{strategy_name}'"
                    )
                    return result

                logger.info(
                    f"CLOSE signal matched position #{matched_pos['id']} "
                    f"({signal.symbol} via {strategy_name})"
                )

                # ── Churn guards ─────────────────────────────────────────────
                # Root cause of Apr 18 breakeven losses: indicators fired CLOSE on
                # the same bar as BUY (short_exit bug). That's fixed in Pine, but
                # belt-and-suspenders here protects against 1-2 bar whipsaws and
                # pure fee churn. SL/TP still fire via position_monitor regardless
                # of these guards — only signal-driven closes are gated.
                close_cfg = get("close_guards") or {}
                min_hold_seconds = int(close_cfg.get("min_hold_seconds", 120))
                min_move_pct = float(close_cfg.get("min_move_pct_to_close", 0.005))  # 0.5%

                entry_price = float(matched_pos.get("entry_price") or 0)
                created_at_str = matched_pos.get("created_at") or ""
                try:
                    opened_ts = datetime.fromisoformat(created_at_str.replace("Z", "")).timestamp()
                except Exception:
                    opened_ts = 0.0
                age_seconds = time.time() - opened_ts if opened_ts else 999999

                if age_seconds < min_hold_seconds:
                    logger.debug(
                        f"CLOSE rejected for {signal.symbol} pos #{matched_pos['id']}: "
                        f"only {age_seconds:.0f}s old (min {min_hold_seconds}s) — likely whipsaw"
                    )
                    _bump_close_filter("blocked_too_new")
                    result["status"] = "close_rejected_too_new"
                    return result

                move_pct = abs(token_price - entry_price) / entry_price if entry_price else 0
                if move_pct < min_move_pct:
                    logger.debug(
                        f"CLOSE rejected for {signal.symbol} pos #{matched_pos['id']}: "
                        f"price moved only {move_pct*100:.2f}% from entry "
                        f"${entry_price:.6f} → ${token_price:.6f} (need {min_move_pct*100:.2f}% to clear fees)"
                    )
                    _bump_close_filter("blocked_low_move")
                    result["status"] = "close_rejected_below_fee_threshold"
                    return result

                # Close via position monitor for proper swap execution
                from app.services.position_monitor import get_position_monitor
                monitor = get_position_monitor()
                await monitor._close_position(matched_pos, token_price, "signal", jupiter=None)

                result["status"] = "closed"
                insert_trade({
                    "signal_type": action_label,
                    "symbol": signal.symbol,
                    "action": "EXECUTE",
                    "amount_sol": matched_pos.get("amount_sol", token_qty),
                    "price_usd": token_price,
                    "confidence_score": signal.confidence_score,
                    "claude_reasoning": claude_resp.reasoning,
                    "wallet_address": self.wallet.public_key,
                    "leverage": 1,
                    "notes": f"Strategy-isolated close ({action_label}): {strategy_name} pos #{matched_pos['id']}",
                    "strategy": strategy_label,
                    "reason": TradeReason.SIGNAL_CLOSE,
                })
                return result

            # Skip Solana-specific pre-trade ops (Kamino + mint resolution) for EVM symbols
            if self._is_evm_symbol(token_symbol):
                target_mint = None  # not used on EVM path
            else:
                # Withdraw from Kamino if needed (auto-withdraw before trade).
                # GATE on not-dry_run: synthetic preflight signals would otherwise
                # broadcast a real on-chain withdraw_all every time the smoke test
                # ran, draining Kamino and racing subsequent sizing fetches.
                # (Caught 2026-05-12 when PENGU preflight reported tradeable=$0
                # because SOL preflight 60s earlier had withdrawn the full pool.)
                if (
                    self.kamino.enabled
                    and self.kamino.auto_withdraw
                    and kamino_usdc > 0
                    and not getattr(signal, "dry_run", False)
                ):
                    try:
                        logger.info(f"Withdrawing {kamino_usdc:.2f} USDC from Kamino before trade")
                        withdraw_result = await self.kamino.withdraw_all(self.wallet.get_keypair())
                        if withdraw_result.get("success"):
                            await self.telegram.send_message(
                                f"Kamino Withdraw: {kamino_usdc:.2f} USDC withdrawn for trade execution"
                            )
                            await asyncio.sleep(2)  # Wait for tx to finalize
                            self.wallet.invalidate_cache()
                        else:
                            logger.warning(f"Kamino withdraw failed: {withdraw_result.get('error')}")
                    except Exception as e:
                        logger.warning(f"Kamino withdraw error (continuing with available balance): {e}")

                # Resolve target token mint address (Solana SPL)
                target_mint = self._resolve_token_mint(token_symbol)

            # ── DRY-RUN EXIT: pre-execution validation complete, swap NOT broadcast.
            # If the signal flagged dry_run=true (webhook pre-flight validator), we
            # bail before any chain-specific swap. All correlation, sizing, risk
            # gates, route detection ran successfully — meaning the function won't
            # blow up on real signals of this shape. Catches UnboundLocalError /
            # routing-dispatch bugs before live money moves.
            if getattr(signal, "dry_run", False):
                result["status"] = "dry_run_pass"
                result["dry_run"] = True
                result["lane"] = (
                    "binance_us" if self._is_binance_symbol(token_symbol)
                    else "evm" if self._is_evm_symbol(token_symbol)
                    else "solana"
                )
                result["tradeable_usd"] = tradeable_usd
                result["trade_usd"] = trade_usd
                result["token_price"] = token_price
                logger.info(
                    f"DRY-RUN pass: {signal.signal_type.value} {token_symbol} "
                    f"lane={result['lane']} tradeable=${tradeable_usd:.2f} "
                    f"trade=${trade_usd:.2f}"
                )
                update_signal_disposition(
                    signal.signal_log_id, "dry_run_pass",
                    reason=f"preflight {result['lane']} tradeable=${tradeable_usd:.2f} trade=${trade_usd:.2f}",
                )
                return result

            # ── Branch by chain: Binance.US CEX (Phase 2) vs EVM (Arbitrum via OpenOcean) vs Solana (Jupiter)
            if self._is_binance_symbol(token_symbol):
                # Binance.US CEX execution path (added 2026-05-09 Phase 2)
                bn = self._get_binance_us()
                bn_symbol = self.BINANCE_TOKENS[token_symbol]

                # Pre-flight: get symbol info for filters + last price
                sym_info = await bn.get_symbol_info(bn_symbol)
                if not sym_info.get("success"):
                    raise RuntimeError(f"Binance.US symbol info fetch failed: {sym_info.get('error')}")
                if sym_info.get("status") != "TRADING":
                    raise RuntimeError(f"Binance.US symbol {bn_symbol} status={sym_info.get('status')} (not TRADING)")
                min_notional = sym_info.get("min_notional", 0)
                step_size = sym_info.get("step_size", 0)

                if signal.signal_type.value == "BUY":
                    if trade_usd < min_notional:
                        raise RuntimeError(
                            f"Trade size ${trade_usd:.2f} below {bn_symbol} min notional ${min_notional}"
                        )
                    logger.info(
                        f"Executing BUY {token_symbol} on Binance.US: ${trade_usd:.2f} USDT market order"
                    )
                    order_result = await bn.place_market_buy_quote(bn_symbol, trade_usd)
                else:
                    # SELL: use base-asset quantity from positions table; quantize to stepSize
                    bn_balance = await bn.get_balance(token_symbol)
                    qty = bn.quantize_qty(bn_balance, step_size) if step_size > 0 else bn_balance
                    if qty <= 0:
                        raise RuntimeError(f"No {token_symbol} balance on Binance.US to sell")
                    if qty * token_price < min_notional:
                        raise RuntimeError(
                            f"Sell size {qty} {token_symbol} (~${qty*token_price:.2f}) below min notional ${min_notional}"
                        )
                    logger.info(
                        f"Executing SELL {qty} {token_symbol} on Binance.US (~${qty*token_price:.2f}) market order"
                    )
                    order_result = await bn.place_market_sell_base(bn_symbol, qty)

                if not order_result.get("success"):
                    raise RuntimeError(
                        f"Binance.US order failed: {order_result.get('error')}"
                    )
                order = order_result["data"]
                # Extract weighted-avg fill price from fills array
                fills = order.get("fills", [])
                exec_qty = float(order.get("executedQty", 0))
                cum_quote = float(order.get("cummulativeQuoteQty", 0))
                avg_price = (cum_quote / exec_qty) if exec_qty > 0 else 0
                # Map to Jupiter-shaped result so downstream code reuses
                swap_result = {
                    "tx_signature": f"binance:{order.get('orderId')}",
                    "price_impact": "n/a",
                    "executed_qty": exec_qty,
                    "avg_price": avg_price,
                    "cum_quote_usdt": cum_quote,
                }
                # Override token_price with actual fill price for downstream sizing/TP-SL math
                if avg_price > 0:
                    token_price = avg_price
                result["status"] = "executed"
                result["tx_signature"] = swap_result["tx_signature"]
                result["chain"] = "binance"
                # Override token_qty with what actually filled (for position record)
                if signal.signal_type.value == "BUY":
                    token_qty = exec_qty
                else:
                    # On sell, "filled" is in token but we record cum_quote (USDC received)
                    token_qty = exec_qty

            elif self._is_evm_symbol(token_symbol):
                # EVM execution path
                evm_executor = self._get_evm_executor()
                evm_wallet = self._get_evm_wallet()

                # Gas-price circuit breaker — skip trade if Arbitrum gas spikes.
                # Default threshold: 0.5 gwei (current normal is ~0.02 gwei, so
                # 25x normal). Configurable via evm_wallet.max_gas_price_gwei.
                evm_cfg = get("evm_wallet") or {}
                max_gwei = float(evm_cfg.get("max_gas_price_gwei", 0.5))
                current_gas_wei = await evm_wallet.get_gas_price_wei(with_buffer=False)
                current_gas_gwei = current_gas_wei / 1e9
                if current_gas_gwei > max_gwei:
                    logger.warning(
                        f"EVM gas-price circuit breaker tripped: {current_gas_gwei:.4f} gwei "
                        f"> threshold {max_gwei} gwei — skipping {token_symbol} trade"
                    )
                    result["status"] = "skipped_gas_too_high"
                    result["chain"] = "arbitrum"
                    return result

                evm_token_addr, evm_token_decimals = self.EVM_TOKENS[token_symbol]

                # Aave V3 JIT auto-withdraw (Phase 3.4)
                # If this is a BUY and wallet USDC < trade_usd + reserve, pull
                # the gap from Aave so the swap doesn't run out of USDC mid-flight.
                if signal.signal_type.value == "BUY":
                    try:
                        from app.services.aave_v3_client import AaveV3Client
                        aave = AaveV3Client()
                        if aave.enabled:
                            wd = await aave.withdraw_for_trade(trade_usd, dry_run=False)
                            if wd.get("success") and not wd.get("skipped"):
                                amt = wd.get("amount_usdc", 0)
                                logger.info(
                                    f"Aave JIT withdraw: ${amt:.2f} USDC pulled "
                                    f"(wallet was ${wd.get('wallet_usdc_before', 0):.2f}, "
                                    f"needed ${wd.get('needed', 0):.2f}) — "
                                    f"tx={wd.get('withdraw_tx', {}).get('tx_hash', '?')[:14]}…"
                                )
                                await self.telegram.send_message(
                                    f"Aave Withdraw: ${amt:.2f} USDC pulled to fund "
                                    f"{token_symbol} BUY"
                                )
                            elif not wd.get("skipped") and not wd.get("success"):
                                logger.warning(
                                    f"Aave JIT withdraw could not cover gap: "
                                    f"{wd.get('reason', 'unknown')}"
                                )
                    except Exception as e:
                        logger.warning(f"Aave JIT withdraw failed: {e}")

                if signal.signal_type.value == "BUY":
                    src_addr, src_dec = self.EVM_USDC_CONTRACT, self.EVM_USDC_DECIMALS
                    dst_addr, dst_dec = evm_token_addr, evm_token_decimals
                    amount_wei = int(trade_usd * (10 ** self.EVM_USDC_DECIMALS))
                else:
                    src_addr, src_dec = evm_token_addr, evm_token_decimals
                    dst_addr, dst_dec = self.EVM_USDC_CONTRACT, self.EVM_USDC_DECIMALS
                    token_amount = trade_usd / token_price if token_price > 0 else 0
                    amount_wei = int(token_amount * (10 ** evm_token_decimals))

                logger.info(
                    f"Executing {signal.signal_type.value} {token_symbol} on EVM (Arbitrum): "
                    f"${trade_usd:.2f} USDC at {leverage}x via OpenOcean"
                )

                evm_result = await evm_executor.execute_swap(
                    src_token=src_addr, src_decimals=src_dec,
                    dst_token=dst_addr, dst_decimals=dst_dec,
                    amount_wei=amount_wei,
                    slippage_bps=200,  # 2% — slightly more than Solana to handle EVM volatility
                    dry_run=False,
                    wait_for_swap_receipt=True,
                    receipt_timeout_s=120,
                )
                # Verify swap actually succeeded on-chain
                receipt = evm_result.get("receipt") or {}
                evm_status = int(receipt.get("status", "0x0"), 16)
                if evm_status != 1:
                    raise RuntimeError(
                        f"EVM swap reverted on-chain: tx={evm_result['swap_tx']['hash']}"
                    )
                # Map EVM result into the same shape as Jupiter for downstream code
                swap_result = {
                    "tx_signature": evm_result["swap_tx"]["hash"],
                    "price_impact": "n/a",  # OpenOcean doesn't return PI in the same format
                }
                result["status"] = "executed"
                result["tx_signature"] = swap_result["tx_signature"]
                result["chain"] = "arbitrum"
            else:
                # Solana execution path (Jupiter) — original flow
                if signal.signal_type.value == "BUY":
                    input_mint = self.jupiter.usdc_mint
                    output_mint = target_mint
                    amount_lamports = int(trade_usd * 1_000_000)
                else:
                    input_mint = target_mint
                    output_mint = self.jupiter.usdc_mint
                    token_amount = trade_usd / token_price if token_price > 0 else 0
                    decimals = self._token_decimals(token_symbol)
                    amount_lamports = int(token_amount * (10 ** decimals))

                logger.info(
                    f"Executing {signal.signal_type.value} {token_symbol}: "
                    f"${trade_usd:.2f} USDC at {leverage}x "
                    f"(swap {input_mint[:8]}..→{output_mint[:8]}..)"
                )

                swap_result = await self.jupiter.execute_swap(
                    keypair=self.wallet.get_keypair(),
                    input_mint=input_mint,
                    output_mint=output_mint,
                    amount_lamports=amount_lamports,
                )

                result["status"] = "executed"
                result["tx_signature"] = swap_result["tx_signature"]
                result["chain"] = "solana"

            # Record trade in SOL risk manager for exposure tracking
            if signal.signal_type.value == "BUY":
                sol_rm.record_trade(token_symbol, trade_usd)

            # Invalidate cache so next balance read is fresh
            self.wallet.invalidate_cache()
            if self._evm_wallet is not None:
                self._evm_wallet.invalidate_cache()

            # Get new balance (Solana SOL only — EVM balance shown via separate dashboard later)
            new_balance = await self.wallet.get_balance_sol()

            # Log trade — chain field tells us whether to look up tx on solscan or arbiscan
            chain_label = result.get("chain", "solana")
            trade_notes = f"Price impact: {swap_result.get('price_impact', '?')} | chain={chain_label}"
            _trade_row_id = insert_trade({
                "timestamp": datetime.utcnow().isoformat(),
                "tx_id": swap_result["tx_signature"],
                "signal_type": signal.signal_type.value,
                "symbol": signal.symbol,
                "action": "EXECUTE",
                "amount_sol": token_qty,
                "amount_usd": trade_usd,
                "price_usd": token_price,
                "fees_sol": 0.000005,  # Base tx fee (rough — EVM gas tracked in tx itself)
                "leverage": leverage,
                "confidence_score": signal.confidence_score,
                "claude_reasoning": claude_resp.reasoning,
                "wallet_address": (
                    "binance_us"  # CEX has no on-chain wallet; sentinel for dashboard chain-detection
                    if chain_label == "binance"
                    else (self._evm_wallet.address if chain_label == "arbitrum"
                          else self.wallet.public_key)
                ),
                "notes": trade_notes,
                "strategy": strategy_label,
                "reason": TradeReason.WEBHOOK,
            })

            # Notify Telegram
            await self.telegram.notify_trade_executed(
                tx_sig=swap_result["tx_signature"],
                action=signal.signal_type.value,
                amount_sol=token_qty,
                price_usd=token_price,
                fees_sol=0.000005,
                new_balance_sol=new_balance,
                symbol=signal.symbol,
                trade_usd=trade_usd,
            )

            # Create position record for TP/SL monitoring (BUY only)
            # Position record powers TP/SL monitoring. As of EVM Phase 4
            # (2026-05-02), position_monitor is chain-aware and routes EVM
            # closes through OpenOcean — so we now create position records
            # for both chains. Signal-driven CLOSE webhooks ALSO route
            # correctly through process_signal for both chains.
            chain_for_position = result.get("chain", "solana")
            if signal.signal_type.value == "BUY":
                # Use signal's ATR if present, otherwise fall back to a percentage of
                # current price. Without this fallback, no-ATR alerts would execute the
                # swap (real money spent) but skip position creation, leaving orphaned
                # tokens in the wallet with no TP/SL monitoring (root cause of the
                # April 19 FARTCOIN orphans + 5 other tokens).
                effective_atr = signal.atr if (signal.atr and signal.atr > 0) else None
                atr_is_fallback = effective_atr is None
                if atr_is_fallback:
                    pos_cfg = get("position_monitor") or {}
                    fallback_pct = float(pos_cfg.get("fallback_atr_pct", 0.025))
                    effective_atr = token_price * fallback_pct
                    logger.warning(
                        f"No ATR in {signal.strategy or 'unknown'} signal for {signal.symbol}; "
                        f"using fallback ATR={effective_atr:.6f} ({fallback_pct*100:.1f}% of "
                        f"price ${token_price:.4f}). Investigate Pine alert payload."
                    )

                tp_mult, sl_mult = self._get_strategy_tp_sl(signal.strategy, signal.symbol, signal.timeframe)
                tp_price = token_price + (effective_atr * tp_mult)
                sl_price = token_price - (effective_atr * sl_mult)

                risk_cfg = get("risk")
                max_positions = risk_cfg.get("max_open_positions", 3)
                open_count = get_position_count("open")

                if open_count < max_positions:
                    pos_id = insert_position({
                        "symbol": signal.symbol,
                        "direction": "long",
                        "strategy": signal.strategy or "",
                        "entry_price": token_price,
                        "amount_sol": token_qty,
                        "amount_usdc": trade_usd,
                        "tp_price": tp_price,
                        "sl_price": sl_price,
                        "entry_tx": swap_result["tx_signature"],
                        "timeframe": signal.timeframe or "",
                        "confidence": signal.confidence_score,
                        "atr": effective_atr,
                        "notes": f"TP=${tp_price:.2f} SL=${sl_price:.2f} ATR={effective_atr:.4f}"
                                 + (" [FALLBACK]" if atr_is_fallback else ""),
                    })
                    logger.info(
                        f"Position #{pos_id} opened: {token_qty:.4f} {token_symbol} @ ${token_price:.4f}, "
                        f"TP=${tp_price:.4f}, SL=${sl_price:.4f}"
                        + (" (fallback ATR)" if atr_is_fallback else "")
                    )
                else:
                    logger.warning(f"Max open positions ({max_positions}) reached, skipping position tracking")

            # Auto-deposit idle USDC back to Kamino after trade (Solana lane)
            if self.kamino.enabled and self.kamino.auto_deposit:
                try:
                    await asyncio.sleep(3)  # Wait for balances to settle
                    usdc_balance = await self.wallet.get_usdc_balance()
                    deposit_result = await self.kamino.deposit_idle(self.wallet.get_keypair(), usdc_balance)
                    if deposit_result.get("success"):
                        deposited = deposit_result["amount_usdc"]
                        await self.telegram.send_message(
                            f"Kamino Deposit: {deposited:.2f} USDC deposited to earn yield"
                        )
                except Exception as e:
                    logger.warning(f"Kamino auto-deposit after trade failed: {e}")

            # Auto-deposit idle USDC back to Aave V3 after trade (EVM lane)
            # Only fires when this trade routed through the EVM lane.
            if result.get("chain") == "arbitrum":
                try:
                    from app.services.aave_v3_client import AaveV3Client
                    aave = AaveV3Client()
                    if aave.enabled and aave.auto_deposit:
                        await asyncio.sleep(3)  # Wait for balances to settle
                        dep = await aave.deposit_idle(dry_run=False)
                        if dep.get("success") and not dep.get("skipped"):
                            amt = dep.get("amount_usdc", 0)
                            tx_hash = dep.get("supply_tx", {}).get("tx_hash", "?")
                            logger.info(f"Aave auto-deposit: ${amt:.2f} USDC supplied (tx={tx_hash[:14]}…)")
                            await self.telegram.send_message(
                                f"Aave Deposit: ${amt:.2f} USDC supplied to earn yield"
                            )
                except Exception as e:
                    logger.warning(f"Aave auto-deposit after trade failed: {e}")

            if result.get("status") == "executed":
                _disp_reason = (
                    f"{result.get('chain', '?')}/${locals().get('trade_usd', 0):.2f} "
                    f"@ ${locals().get('token_price', 0):.4f} → "
                    f"{(result.get('tx_signature') or '')[:18]}"
                )
                update_signal_disposition(
                    signal.signal_log_id, "executed", reason=_disp_reason,
                    trade_id=locals().get("_trade_row_id"),
                )

            return result

        except Exception as e:
            logger.exception(f"Trade engine error: {e}")
            result["status"] = "error"
            result["error"] = str(e)

            # Detect swap-execution failures vs generic engine errors so we can
            # log them to the trades DB + send a focused Telegram. Without this,
            # silent swap failures look like missing webhooks (see PNUT/Raydium
            # 0x1d incident 2026-05-07: signal received → Claude approved → swap
            # rejected → no DB record → user thought webhook was lost).
            err_text = str(e)
            is_swap_failure = any(marker in err_text for marker in (
                "Transaction failed",       # Jupiter/Solana RPC error
                "swap reverted",            # EVM on-chain revert
                "InstructionError",         # Solana program error
                "custom program error",     # Solana program error
                "OpenOceanError",           # OpenOcean aggregator error
                "AlertsRestApiError",       # rare, but possible
            ))

            if is_swap_failure:
                # Pull a short, human-readable reason from the noise. Solana
                # RPC errors often dump 4KB+ of program logs; we want just the
                # actionable bit.
                reason = _summarize_swap_error(err_text)

                # Best-effort variable extraction — the swap call lives well
                # after these bindings (line 985+), so they should all be
                # available. Defensive defaults for early-exit edge cases.
                _trade_usd = locals().get("trade_usd", 0.0) or 0.0
                _token_price = locals().get("token_price", 0.0) or 0.0
                _strategy = locals().get("strategy_label", signal.strategy or "")

                # Insert a failed-trade record so the dashboard transaction log
                # shows it instead of the signal looking like it vanished.
                try:
                    insert_trade({
                        "signal_type": signal.signal_type.value,
                        "symbol": signal.symbol,
                        "action": f"{signal.signal_type.value}_FAILED",
                        "amount_sol": 0,
                        "amount_usd": _trade_usd,
                        "price_usd": _token_price,
                        "fees_sol": 0,
                        "leverage": locals().get("leverage", 1),
                        "wallet_address": (self._evm_wallet.address if self._is_evm_symbol(
                            signal.symbol.replace("USDT", "").replace("USD", "").replace(".P", "")
                        ) and self._evm_wallet else self.wallet.public_key),
                        "confidence_score": signal.confidence_score,
                        "claude_reasoning": locals().get("claude_resp", None) and getattr(
                            locals().get("claude_resp"), "reasoning", "") or "",
                        "notes": f"SWAP FAILED — no position opened. Reason: {reason[:500]}",
                        "strategy": _strategy,
                        "reason": "swap_failed",
                    })
                except Exception as db_err:
                    logger.warning(f"Failed to record swap failure to trades DB: {db_err}")

                # Focused Telegram notification (not the giant program-log dump)
                await self.telegram.notify_swap_failed(
                    symbol=signal.symbol,
                    action=signal.signal_type.value,
                    trade_usd=_trade_usd,
                    error_summary=reason,
                    strategy=_strategy,
                )
                update_signal_disposition(
                    signal.signal_log_id, "failed_swap",
                    reason=f"swap rejected: {reason[:200]}",
                )
            else:
                # Non-swap engine error — fall back to the generic notifier
                await self.telegram.notify_error(
                    str(e), f"Signal: {signal.signal_type.value} {signal.symbol}"
                )
                update_signal_disposition(
                    signal.signal_log_id, "failed_engine_error",
                    reason=str(e)[:200],
                )
            return result

    # Well-known Solana token mints
    _KNOWN_MINTS = {
        "SOL": "So11111111111111111111111111111111111111112",
        "USDC": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
        "JTO": "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
        "WIF": "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm",
        "BONK": "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263",
        "PYTH": "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
        "RAY": "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
        "ETH": "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
        "ORCA": "orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE",
        "RENDER": "rndrizKT3MK1iimdxRdWabcF7Zg7AR5T4nud4EkHBof",
        "W": "85VBFQZC9TZkfaptBWjvUw7YbZjy52A6mjtPGjstQAmQ",
        "DOG": "dog1viwbb2vWDpER5FrJ4YFG6gq6XuyFohUe9TXN65u",
        "JUP": "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        "PENGU": "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
        "FARTCOIN": "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
        "POPCAT": "7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr",
        "MEW": "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",
        "PNUT": "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
        "MOODENG": "ED5nyyWEzpPPiWimP8vYm7sD7TD3LAt3Q3gRTWHzPJBY",
        "HNT": "hntyVP6YFm1Hg25TN9WGLqM12b8TQmcknKrdu1oxWux",
        "DRIFT": "DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7",
        "TNSR": "TNSRxcUxoT9xBG3de7PiJyTDYu7kskLqcpddxnEJAS6",
        # Tier 3 additions (2026-05-02) — Jupiter-tradeable, Coinbase/OKX/Binance.US data
        "ME":   "MEFNBXixkEbait3xn9bkm8WsJzXtVsaJEn4c8Sam21u",
        "KMNO": "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
        "DBR":  "DBRiDgJAMsM95moTzJs7M9LnkGErpbv9v6CUR1DXnUu5",
        "ACT":  "GJAFwWjJ3vnTsrQVabjBVK2TYB1YtRCQXRDfDgUnpump",
        "GOAT": "CzLSujWBLFsSjncfkh59rUFqvafWcY5tzedWJSuypump",
        "ZEUS": "ZEUS1aR7aX8DFFJf5QjWj2ftDDdNTroMNGo8YoQm3Gq",
    }

    _TOKEN_DECIMALS = {
        "SOL": 9, "USDC": 6, "JTO": 9, "WIF": 6,
        "BONK": 5, "PYTH": 6, "RAY": 6, "ETH": 8, "ORCA": 6,
        "RENDER": 8, "W": 6, "DOG": 5,
        "JUP": 6, "PENGU": 6, "FARTCOIN": 6, "POPCAT": 9,
        "MEW": 5, "PNUT": 6, "MOODENG": 6,
        "HNT": 8, "DRIFT": 6, "TNSR": 9,
        "ME": 6, "KMNO": 6, "DBR": 6, "ACT": 6, "GOAT": 6, "ZEUS": 6,
    }

    def _resolve_token_mint(self, symbol: str) -> str:
        """Resolve token symbol to Solana mint address."""
        # Check well-known mints first, then rebalancer config
        if symbol in self._KNOWN_MINTS:
            return self._KNOWN_MINTS[symbol]
        rebal_cfg = get("rebalancer") or {}
        token_mints = rebal_cfg.get("token_mints", {})
        if symbol in token_mints:
            return token_mints[symbol]
        # Fallback to SOL mint if unknown
        logger.warning(f"Unknown token mint for {symbol}, falling back to SOL")
        return self._KNOWN_MINTS["SOL"]

    def _token_decimals(self, symbol: str) -> int:
        """Get decimal places for a token (for lamport conversion)."""
        return self._TOKEN_DECIMALS.get(symbol, 9)

    @staticmethod
    def _get_strategy_tp_sl(
        strategy: Optional[str],
        symbol: Optional[str] = None,
        timeframe: Optional[str] = None,
    ) -> tuple[float, float]:
        """Get TP/SL multipliers for a strategy/token/TF, falling back to global defaults.

        Precedence (highest first):
          1. strategy_token_tf_overrides[strategy][token][tf] — from tp_sl_sweep winners
          2. position_monitor.token_overrides[token].sl_multiplier — manual SL widening
          3. strategy_profiles[strategy] — hand-tuned per-strategy defaults
          4. position_monitor.{tp_multiplier, sl_multiplier} — global defaults
        """
        pos_cfg = get("position_monitor") or {}
        default_tp = pos_cfg.get("tp_multiplier", 4.0)
        default_sl = pos_cfg.get("sl_multiplier", 1.5)

        tp_mult, sl_mult = default_tp, default_sl

        # Strategy-specific overrides (hand-tuned)
        if strategy:
            strategy_cfg = get("strategy_profiles") or {}
            strategy_upper = strategy.upper()
            for name, profile in strategy_cfg.items():
                if strategy_upper.startswith(name.upper()):
                    tp_mult = profile.get("tp_multiplier", default_tp)
                    sl_mult = profile.get("sl_multiplier", default_sl)
                    break

        # Token-specific SL override (e.g., memecoins need wider stops)
        token_key = None
        if symbol:
            token_key = symbol.upper().replace("USDT", "").replace("USD", "").replace(".P", "")
            token_overrides = pos_cfg.get("token_overrides") or {}
            override = token_overrides.get(token_key)
            if override and "sl_multiplier" in override:
                sl_mult = override["sl_multiplier"]

        # Sweep-generated per-(strategy, token, tf) overrides — highest precedence.
        # Pine sends "EMA Ribbon v1.0" / "240"; YAML is keyed by "EMA Ribbon" / "4H".
        if strategy and token_key and timeframe:
            sweep = _load_tpsl_overrides()
            strat_norm = _normalize_strategy_name(strategy)
            tf_norm = _normalize_timeframe(timeframe)
            slot = sweep.get(strat_norm, {}).get(token_key, {}).get(tf_norm)
            if slot:
                tp_mult = slot.get("atr_tp_mult", tp_mult)
                sl_mult = slot.get("atr_sl_mult", sl_mult)

        return tp_mult, sl_mult

    async def shutdown(self):
        self._running = False
        await self.jupiter.close()
        await self.wallet.close()
        await self.telegram.close()
        await self.news.close()
        await self.kamino.close()
